---
metrics:
  - name: PRs merged by repository
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    series:
      - prs_merged
    values:
      - =;;;kubernetes/kubernetes,kubernetes/test-infra,kubernetes/kubernetes.github.io,kubernetes/kops,kubernetes/contrib,kubernetes/console,kubernetes/dashboard,kubernetes/kubernetes-console,kubernetes/application-dm-templates,kubernetes/charts,kubernetes/deployment-manager,kubernetes/helm,kubernetes/minikube,kubernetes/community,kubernetes/heapster,kubernetes-incubator/service-catalog,kubernetes-incubator/cri-o,kubernetes-incubator/ocid,kubernetes/ingress,kubernetes-incubator/kargo,kubernetes-incubator/kubespray,kubernetes-incubator/kompose,kubernetes/kompose,kubernetes-incubator/bootkube,kubernetes/features,kubernetes-incubator/kube-aws,kubernetes/kubeadm,kubernetes-incubator/cri-containerd,kubernetes-incubator/external-dns,kubernetes-incubator/external-storage,kubernetes/autoscaler,kubernetes/client-go,kubernetes/release,kubernetes-incubator/client-python,kubernetes/kube-state-metrics,kubernetes/kubernetes-anywhere,kubernetes/kube-deploy,kubernetes/frakti,kubernetes/node-problem-detector,kubernetes/dns,kubernetes-incubator/cri-tools,kubernetes/examples,kubernetes/perf-tests,kubernetes-incubator/apiserver-builder,kubernetes-incubator/rktlet,kubernetes/rktlet,kubernetes-incubator/node-feature-discovery,kubernetes/gengo,kubernetes-client/java,kubernetes/git-sync
  - name: PRs merged by repository groups
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    series:
      - group_prs_merged
    values:
      - =;;;API machinery,Apps,Autoscaling and monitoring,Clients,Cluster lifecycle,Contrib,Docs,Kubernetes,Misc,Multi-cluster,Networking,Node,Project,Project infra,Storage,UI
  - name: PRs approved and awaiting approval
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: d,w7,m7,q7,y7
    series:
      - prs_approve_state_approved
      - prs_approve_state_awaiting
    values:
      - =;;;All,API machinery,Apps,Autoscaling and monitoring,Clients,Cluster lifecycle,Contrib,Docs,Kubernetes,Misc,Multi-cluster,Networking,Node,Project,Project infra,Storage,UI
  - name: Issues closed broken down by SIG and kind
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    series:
      - issues_closed_labels_sig_kind
    values:
      - =;;-;All,node,api-machinery,network,storage,cli,cluster-lifecycle,apps,scheduling,federation,auth,testing,scalability,aws,autoscaling,release,instrumentation,openstack,docs,contributor-experience,azure,architecture,cluster-ops,service-catalog,windows,onprem,ui,contrib-ex,rktnetes,big-data,gcp,cluster-federation,cluster-fifecycle,pm;All,flake,bug,api-change,documentation,feature,support,design,enhancement,cleanup,old-docs,new-api,upgrade-test-failure,friction,example,velocity-improvement,technical-debt,gsoc,e2e-test-failure,discussion,refactoring,internal,question,ecosystem-enablement,testing,discuss,postmortem,refactor,tracking-issue,mesos-flake,policy,test,docs,pm,repository-infra,workaround-removal,meta,regression,duplicate,help-wanted,technical-debut
  - name: Issues opened broken down by repo group
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    series:
      - issues_opened
    values:
      - =;;;All,API machinery,Apps,Autoscaling and monitoring,Clients,Cluster lifecycle,Contrib,Docs,Kubernetes,Misc,Multi-cluster,Networking,Node,Project,Project infra,Storage,UI
  - name: Issues closed broken down by repo group
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    series:
      - issues_closed
    values:
      - =;;;All,API machinery,Apps,Autoscaling and monitoring,Clients,Cluster lifecycle,Contrib,Docs,Kubernetes,Misc,Multi-cluster,Networking,Node,Project,Project infra,Storage,UI
  - name: Companies velocity metrics
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    series:
      - =company_;;_;all,prometheus,prometheus_alertmanager,prometheus_blackbox_exporter,prometheus_build_tools,prometheus_busybox,prometheus_client_golang,prometheus_client_java,prometheus_client_model,prometheus_client_python,prometheus_client_ruby,prometheus_cloudwatch_exporter,prometheus_collectd_exporter,prometheus_common,prometheus_consul_exporter,prometheus_demo,prometheus_distro_pkgs,prometheus_docs,prometheus_golang_builder,prometheus_graphite_exporter,prometheus_haproxy_exporter,prometheus_host_exporter,prometheus_hystrix,prometheus_influxdb_exporter,prometheus_jmx_exporter,prometheus_log,prometheus_memcached_exporter,prometheus_mesos_exporter,prometheus_migrate,prometheus_mysqld_exporter,prometheus_nagios_plugins,prometheus_node_exporter,prometheus_procfs,prometheus_prom2json,prometheus_prombench,prometheus_promdash,prometheus_prometheus,prometheus_prometheus_api_client_ruby,prometheus_prometheus_cli,prometheus_prometheus_github_io,prometheus_promu,prometheus_pushgateway,prometheus_snmp_exporter,prometheus_statsd_bridge,prometheus_statsd_exporter,prometheus_tsdb,prometheus_utils;activity,authors,issues,prs,commits,review_comments,issue_comments,commit_comments,comments
    values:
      - =;;;Airtame,AnchorFree,Aptarus,BENGLER,Bytes and Butter,Canonical,Cloudflare,ContaAzul,CoreOS,Digidentity,FINN.no,Google,Headspace,HolidayCheck,Inuits,Jusbrasil,Kickstarter,Magnet Digital,Red Hat,Self,SkiTravelGroup,SoundCloud,Stack Exchange,Tazedirekt,Telemetry.com,Unicon,Weaveworks,Wise2c,imgix,startuphero.es
