---
tags:
  - name: Repository aliases
    sql: repo_aliases_tags
    series_name: all_repo_names
    name_tag: all_repo_names_name
    value_tag: all_repo_names_value
  - name: Repository groups including All
    sql: repo_groups_tags_with_all
    series_name: all_repo_groups
    name_tag: all_repo_group_name
    value_tag: all_repo_group_value
  - name: Repository groups without All
    sql: repo_groups_tags
    series_name: repo_groups
    name_tag: repo_group_name
    value_tag: repo_group_value
  - name: Companies
    sql: companies_tags
    series_name: companies
    name_tag: companies_name
  - name: Priority labels with all
    sql: labels_priorities_tags_with_all
    series_name: priority_labels_with_all
    name_tag: priority_labels_name_with_all
    value_tag: priority_labels_value_with_all
