---
metrics:
  - name: Countries stats cumulative
    series_name_or_func: multi_row_multi_column
    sql: countries_cum
    periods: m
    multi_value: true
    merge_series: countriescum
  - name: Gender stats (committers)
    series_name_or_func: multi_row_multi_column
    sql: committers_gender
    periods: w,m,q,y
    multi_value: true
    merge_series: sex
  - name: Gender stats cumulative (committers)
    series_name_or_func: multi_row_multi_column
    sql: committers_gender_cum
    periods: m
    multi_value: true
    merge_series: sexcum
  - name: Countries stats (committers)
    series_name_or_func: multi_row_multi_column
    sql: committers_countries
    periods: w,m,q,y
    multi_value: true
    merge_series: countries
  - name: Countries stats cumulative (committers)
    series_name_or_func: multi_row_multi_column
    sql: committers_countries_cum
    periods: m
    multi_value: true
    merge_series: countriescum
  - name: Timezone stats
    series_name_or_func: multi_row_multi_column
    sql: tz
    periods: h,d,w,m,q,y
    aggregate: 1,7
    skip: h7,w7,m7,q7,y7
    multi_value: true
    merge_series: tz
  - name: Timezone stats (committers)
    series_name_or_func: multi_row_multi_column
    sql: committers_tz
    periods: h,d,w,m,q,y
    aggregate: 1,7
    skip: h7,w7,m7,q7,y7
    multi_value: true
    merge_series: tz
  - name: New contributors table
    series_name_or_func: multi_row_single_column
    sql: new_contributors_data
    custom_data: true
    merge_series: new_contributors_data
    periods: h
  - name: Company PRs in repository groups
    sql: company_prs
    series_name_or_func: company_prs
    histogram: true
    annotations_ranges: true
  - name: GitHub activity
    series_name_or_func: events_h
    sql: events
    periods: h
