{
 "title": "Companies velocity",
 "tags": [
  "companies",
  "dashboard",
  "tuf"
 ],
 "time": { "from": "now-3y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "full_name",
    "query": "SHOW TAG VALUES WITH KEY = full_name"
   },
   { "name": "period", "label": "Period", "query": "d,w,m,q,y" },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "SHOW TAG VALUES WITH KEY = all_repo_group_name"
   },
   {
    "name": "repogroup",
    "query": "SHOW TAG VALUES WITH KEY = all_repo_group_value where all_repo_group_name =~ /^[[repogroup_name]]$/"
   },
   {
    "name": "companies",
    "label": "Companies",
    "query": "SHOW TAG VALUES WITH KEY = companies_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Companies activity ([[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Measures activity of companies users. Activity is defined as: creating issue, PR, commit, comment. Independent means developers working on their own.",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "GitHub activity" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "sig_federation_d",
     "query": "SELECT /^[[companies]]$/ FROM \"company_[[repogroup]]_activity_[[period]]\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Companies active authors ([[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Measures number of company developers active in given period. Activity is defined as: creating issue, PR, commit, comment. Independent means developers working on their own.",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Active authors" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "sig_federation_d",
     "query": "SELECT /^[[companies]]$/ FROM \"company_[[repogroup]]_authors_[[period]]\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Issues created by company ([[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Number of issues created by company developers. Independent means developers working on their own.",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Created issues" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "sig_federation_d",
     "query": "SELECT /^[[companies]]$/ FROM \"company_[[repogroup]]_issues_[[period]]\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PRs created by company ([[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Number of PRs created by company developers. Independent means developers working on their own.",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Created pull requests" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "sig_federation_d",
     "query": "SELECT /^[[companies]]$/ FROM \"company_[[repogroup]]_prs_[[period]]\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Company commits ([[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Number of commits created by company developers. Independent means developers working on their own.",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "sig_federation_d",
     "query": "SELECT /^[[companies]]$/ FROM \"company_[[repogroup]]_commits_[[period]]\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Company comments ([[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Number of comments written by company developers. Counts comments on Issues, PRs and reviews. Independent means developers working on their own.",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short", "label": "Comments" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "sig_federation_d",
     "query": "SELECT /^[[companies]]$/ FROM \"company_[[repogroup]]_comments_[[period]]\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}