insert into gha_countries(code, name) values('af', 'Afghanistan');
insert into gha_countries(code, name) values('ax', 'Åland Islands');
insert into gha_countries(code, name) values('al', 'Albania');
insert into gha_countries(code, name) values('dz', 'Algeria');
insert into gha_countries(code, name) values('as', 'American Samoa');
insert into gha_countries(code, name) values('ad', 'Andorra');
insert into gha_countries(code, name) values('ao', 'Angola');
insert into gha_countries(code, name) values('ai', 'Anguilla');
insert into gha_countries(code, name) values('aq', 'Antarctica');
insert into gha_countries(code, name) values('ag', 'Antigua and Barbuda');
insert into gha_countries(code, name) values('ar', 'Argentina');
insert into gha_countries(code, name) values('am', 'Armenia');
insert into gha_countries(code, name) values('aw', 'Aruba');
insert into gha_countries(code, name) values('au', 'Australia');
insert into gha_countries(code, name) values('at', 'Austria');
insert into gha_countries(code, name) values('az', 'Azerbaijan');
insert into gha_countries(code, name) values('bs', 'Bahamas');
insert into gha_countries(code, name) values('bh', 'Bahrain');
insert into gha_countries(code, name) values('bd', 'Bangladesh');
insert into gha_countries(code, name) values('bb', 'Barbados');
insert into gha_countries(code, name) values('by', 'Belarus');
insert into gha_countries(code, name) values('be', 'Belgium');
insert into gha_countries(code, name) values('bz', 'Belize');
insert into gha_countries(code, name) values('bj', 'Benin');
insert into gha_countries(code, name) values('bm', 'Bermuda');
insert into gha_countries(code, name) values('bt', 'Bhutan');
insert into gha_countries(code, name) values('bo', 'Bolivia, Plurinational State of');
insert into gha_countries(code, name) values('bq', 'Bonaire, Sint Eustatius and Saba');
insert into gha_countries(code, name) values('ba', 'Bosnia and Herzegovina');
insert into gha_countries(code, name) values('bw', 'Botswana');
insert into gha_countries(code, name) values('bv', 'Bouvet Island');
insert into gha_countries(code, name) values('br', 'Brazil');
insert into gha_countries(code, name) values('io', 'British Indian Ocean Territory');
insert into gha_countries(code, name) values('bn', 'Brunei Darussalam');
insert into gha_countries(code, name) values('bg', 'Bulgaria');
insert into gha_countries(code, name) values('bf', 'Burkina Faso');
insert into gha_countries(code, name) values('bi', 'Burundi');
insert into gha_countries(code, name) values('kh', 'Cambodia');
insert into gha_countries(code, name) values('cm', 'Cameroon');
insert into gha_countries(code, name) values('ca', 'Canada');
insert into gha_countries(code, name) values('cv', 'Cape Verde');
insert into gha_countries(code, name) values('ky', 'Cayman Islands');
insert into gha_countries(code, name) values('cf', 'Central African Republic');
insert into gha_countries(code, name) values('td', 'Chad');
insert into gha_countries(code, name) values('cl', 'Chile');
insert into gha_countries(code, name) values('cn', 'China');
insert into gha_countries(code, name) values('cx', 'Christmas Island');
insert into gha_countries(code, name) values('cc', 'Cocos (Keeling) Islands');
insert into gha_countries(code, name) values('co', 'Colombia');
insert into gha_countries(code, name) values('km', 'Comoros');
insert into gha_countries(code, name) values('cg', 'Congo');
insert into gha_countries(code, name) values('cd', 'Congo, the Democratic Republic of the');
insert into gha_countries(code, name) values('ck', 'Cook Islands');
insert into gha_countries(code, name) values('cr', 'Costa Rica');
insert into gha_countries(code, name) values('ci', 'Côte D''ivoire');
insert into gha_countries(code, name) values('hr', 'Croatia');
insert into gha_countries(code, name) values('cu', 'Cuba');
insert into gha_countries(code, name) values('cw', 'Curaçao');
insert into gha_countries(code, name) values('cy', 'Cyprus');
insert into gha_countries(code, name) values('cz', 'Czech Republic');
insert into gha_countries(code, name) values('dk', 'Denmark');
insert into gha_countries(code, name) values('dj', 'Djibouti');
insert into gha_countries(code, name) values('dm', 'Dominica');
insert into gha_countries(code, name) values('do', 'Dominican Republic');
insert into gha_countries(code, name) values('ec', 'Ecuador');
insert into gha_countries(code, name) values('eg', 'Egypt');
insert into gha_countries(code, name) values('sv', 'El Salvador');
insert into gha_countries(code, name) values('gq', 'Equatorial Guinea');
insert into gha_countries(code, name) values('er', 'Eritrea');
insert into gha_countries(code, name) values('ee', 'Estonia');
insert into gha_countries(code, name) values('et', 'Ethiopia');
insert into gha_countries(code, name) values('fk', 'Falkland Islands (Malvinas)');
insert into gha_countries(code, name) values('fo', 'Faroe Islands');
insert into gha_countries(code, name) values('fj', 'Fiji');
insert into gha_countries(code, name) values('fi', 'Finland');
insert into gha_countries(code, name) values('fr', 'France');
insert into gha_countries(code, name) values('gf', 'French Guiana');
insert into gha_countries(code, name) values('pf', 'French Polynesia');
insert into gha_countries(code, name) values('tf', 'French Southern Territories');
insert into gha_countries(code, name) values('ga', 'Gabon');
insert into gha_countries(code, name) values('gm', 'Gambia');
insert into gha_countries(code, name) values('ge', 'Georgia');
insert into gha_countries(code, name) values('de', 'Germany');
insert into gha_countries(code, name) values('gh', 'Ghana');
insert into gha_countries(code, name) values('gi', 'Gibraltar');
insert into gha_countries(code, name) values('gr', 'Greece');
insert into gha_countries(code, name) values('gl', 'Greenland');
insert into gha_countries(code, name) values('gd', 'Grenada');
insert into gha_countries(code, name) values('gp', 'Guadeloupe');
insert into gha_countries(code, name) values('gu', 'Guam');
insert into gha_countries(code, name) values('gt', 'Guatemala');
insert into gha_countries(code, name) values('gg', 'Guernsey');
insert into gha_countries(code, name) values('gn', 'Guinea');
insert into gha_countries(code, name) values('gw', 'Guinea-Bissau');
insert into gha_countries(code, name) values('gy', 'Guyana');
insert into gha_countries(code, name) values('ht', 'Haiti');
insert into gha_countries(code, name) values('hm', 'Heard Island and Mcdonald Islands');
insert into gha_countries(code, name) values('va', 'Holy See (Vatican City State)');
insert into gha_countries(code, name) values('hn', 'Honduras');
insert into gha_countries(code, name) values('hk', 'Hong Kong');
insert into gha_countries(code, name) values('hu', 'Hungary');
insert into gha_countries(code, name) values('is', 'Iceland');
insert into gha_countries(code, name) values('in', 'India');
insert into gha_countries(code, name) values('id', 'Indonesia');
insert into gha_countries(code, name) values('ir', 'Iran, Islamic Republic of');
insert into gha_countries(code, name) values('iq', 'Iraq');
insert into gha_countries(code, name) values('ie', 'Ireland');
insert into gha_countries(code, name) values('im', 'Isle of Man');
insert into gha_countries(code, name) values('il', 'Israel');
insert into gha_countries(code, name) values('it', 'Italy');
insert into gha_countries(code, name) values('jm', 'Jamaica');
insert into gha_countries(code, name) values('jp', 'Japan');
insert into gha_countries(code, name) values('je', 'Jersey');
insert into gha_countries(code, name) values('jo', 'Jordan');
insert into gha_countries(code, name) values('kz', 'Kazakhstan');
insert into gha_countries(code, name) values('ke', 'Kenya');
insert into gha_countries(code, name) values('ki', 'Kiribati');
insert into gha_countries(code, name) values('kp', 'Korea, Democratic People''s Republic of');
insert into gha_countries(code, name) values('kr', 'Korea, Republic of');
insert into gha_countries(code, name) values('kw', 'Kuwait');
insert into gha_countries(code, name) values('kg', 'Kyrgyzstan');
insert into gha_countries(code, name) values('la', 'Lao People''s Democratic Republic');
insert into gha_countries(code, name) values('lv', 'Latvia');
insert into gha_countries(code, name) values('lb', 'Lebanon');
insert into gha_countries(code, name) values('ls', 'Lesotho');
insert into gha_countries(code, name) values('lr', 'Liberia');
insert into gha_countries(code, name) values('ly', 'Libya');
insert into gha_countries(code, name) values('li', 'Liechtenstein');
insert into gha_countries(code, name) values('lt', 'Lithuania');
insert into gha_countries(code, name) values('lu', 'Luxembourg');
insert into gha_countries(code, name) values('mo', 'Macao');
insert into gha_countries(code, name) values('mk', 'Macedonia, the Former Yugoslav Republic of');
insert into gha_countries(code, name) values('mg', 'Madagascar');
insert into gha_countries(code, name) values('mw', 'Malawi');
insert into gha_countries(code, name) values('my', 'Malaysia');
insert into gha_countries(code, name) values('mv', 'Maldives');
insert into gha_countries(code, name) values('ml', 'Mali');
insert into gha_countries(code, name) values('mt', 'Malta');
insert into gha_countries(code, name) values('mh', 'Marshall Islands');
insert into gha_countries(code, name) values('mq', 'Martinique');
insert into gha_countries(code, name) values('mr', 'Mauritania');
insert into gha_countries(code, name) values('mu', 'Mauritius');
insert into gha_countries(code, name) values('yt', 'Mayotte');
insert into gha_countries(code, name) values('mx', 'Mexico');
insert into gha_countries(code, name) values('fm', 'Micronesia, Federated States of');
insert into gha_countries(code, name) values('md', 'Moldova, Republic of');
insert into gha_countries(code, name) values('mc', 'Monaco');
insert into gha_countries(code, name) values('mn', 'Mongolia');
insert into gha_countries(code, name) values('me', 'Montenegro');
insert into gha_countries(code, name) values('ms', 'Montserrat');
insert into gha_countries(code, name) values('ma', 'Morocco');
insert into gha_countries(code, name) values('mz', 'Mozambique');
insert into gha_countries(code, name) values('mm', 'Myanmar');
insert into gha_countries(code, name) values('na', 'Namibia');
insert into gha_countries(code, name) values('nr', 'Nauru');
insert into gha_countries(code, name) values('np', 'Nepal');
insert into gha_countries(code, name) values('nl', 'Netherlands');
insert into gha_countries(code, name) values('nc', 'New Caledonia');
insert into gha_countries(code, name) values('nz', 'New Zealand');
insert into gha_countries(code, name) values('ni', 'Nicaragua');
insert into gha_countries(code, name) values('ne', 'Niger');
insert into gha_countries(code, name) values('ng', 'Nigeria');
insert into gha_countries(code, name) values('nu', 'Niue');
insert into gha_countries(code, name) values('nf', 'Norfolk Island');
insert into gha_countries(code, name) values('mp', 'Northern Mariana Islands');
insert into gha_countries(code, name) values('no', 'Norway');
insert into gha_countries(code, name) values('om', 'Oman');
insert into gha_countries(code, name) values('pk', 'Pakistan');
insert into gha_countries(code, name) values('pw', 'Palau');
insert into gha_countries(code, name) values('ps', 'Palestine, State of');
insert into gha_countries(code, name) values('pa', 'Panama');
insert into gha_countries(code, name) values('pg', 'Papua New Guinea');
insert into gha_countries(code, name) values('py', 'Paraguay');
insert into gha_countries(code, name) values('pe', 'Peru');
insert into gha_countries(code, name) values('ph', 'Philippines');
insert into gha_countries(code, name) values('pn', 'Pitcairn');
insert into gha_countries(code, name) values('pl', 'Poland');
insert into gha_countries(code, name) values('pt', 'Portugal');
insert into gha_countries(code, name) values('pr', 'Puerto Rico');
insert into gha_countries(code, name) values('qa', 'Qatar');
insert into gha_countries(code, name) values('re', 'Réunion');
insert into gha_countries(code, name) values('ro', 'Romania');
insert into gha_countries(code, name) values('ru', 'Russian Federation');
insert into gha_countries(code, name) values('rw', 'Rwanda');
insert into gha_countries(code, name) values('bl', 'Saint Barthélemy');
insert into gha_countries(code, name) values('sh', 'Saint Helena, Ascension and Tristan da Cunha');
insert into gha_countries(code, name) values('kn', 'Saint Kitts and Nevis');
insert into gha_countries(code, name) values('lc', 'Saint Lucia');
insert into gha_countries(code, name) values('mf', 'Saint Martin (French Part)');
insert into gha_countries(code, name) values('pm', 'Saint Pierre and Miquelon');
insert into gha_countries(code, name) values('vc', 'Saint Vincent and the Grenadines');
insert into gha_countries(code, name) values('ws', 'Samoa');
insert into gha_countries(code, name) values('sm', 'San Marino');
insert into gha_countries(code, name) values('st', 'Sao Tome and Principe');
insert into gha_countries(code, name) values('sa', 'Saudi Arabia');
insert into gha_countries(code, name) values('sn', 'Senegal');
insert into gha_countries(code, name) values('rs', 'Serbia');
insert into gha_countries(code, name) values('sc', 'Seychelles');
insert into gha_countries(code, name) values('sl', 'Sierra Leone');
insert into gha_countries(code, name) values('sg', 'Singapore');
insert into gha_countries(code, name) values('sx', 'Sint Maarten (Dutch Part)');
insert into gha_countries(code, name) values('sk', 'Slovakia');
insert into gha_countries(code, name) values('si', 'Slovenia');
insert into gha_countries(code, name) values('sb', 'Solomon Islands');
insert into gha_countries(code, name) values('so', 'Somalia');
insert into gha_countries(code, name) values('za', 'South Africa');
insert into gha_countries(code, name) values('gs', 'South Georgia and the South Sandwich Islands');
insert into gha_countries(code, name) values('ss', 'South Sudan');
insert into gha_countries(code, name) values('es', 'Spain');
insert into gha_countries(code, name) values('lk', 'Sri Lanka');
insert into gha_countries(code, name) values('sd', 'Sudan');
insert into gha_countries(code, name) values('sr', 'Suriname');
insert into gha_countries(code, name) values('sj', 'Svalbard and Jan Mayen');
insert into gha_countries(code, name) values('sz', 'Swaziland');
insert into gha_countries(code, name) values('se', 'Sweden');
insert into gha_countries(code, name) values('ch', 'Switzerland');
insert into gha_countries(code, name) values('sy', 'Syrian Arab Republic');
insert into gha_countries(code, name) values('tw', 'Taiwan, Province of China');
insert into gha_countries(code, name) values('tj', 'Tajikistan');
insert into gha_countries(code, name) values('tz', 'Tanzania, United Republic of');
insert into gha_countries(code, name) values('th', 'Thailand');
insert into gha_countries(code, name) values('tl', 'Timor-Leste');
insert into gha_countries(code, name) values('tg', 'Togo');
insert into gha_countries(code, name) values('tk', 'Tokelau');
insert into gha_countries(code, name) values('to', 'Tonga');
insert into gha_countries(code, name) values('tt', 'Trinidad and Tobago');
insert into gha_countries(code, name) values('tn', 'Tunisia');
insert into gha_countries(code, name) values('tr', 'Turkey');
insert into gha_countries(code, name) values('tm', 'Turkmenistan');
insert into gha_countries(code, name) values('tc', 'Turks and Caicos Islands');
insert into gha_countries(code, name) values('tv', 'Tuvalu');
insert into gha_countries(code, name) values('ug', 'Uganda');
insert into gha_countries(code, name) values('ua', 'Ukraine');
insert into gha_countries(code, name) values('ae', 'United Arab Emirates');
insert into gha_countries(code, name) values('gb', 'United Kingdom');
insert into gha_countries(code, name) values('us', 'United States');
insert into gha_countries(code, name) values('um', 'United States Minor Outlying Islands');
insert into gha_countries(code, name) values('uy', 'Uruguay');
insert into gha_countries(code, name) values('uz', 'Uzbekistan');
insert into gha_countries(code, name) values('vu', 'Vanuatu');
insert into gha_countries(code, name) values('ve', 'Venezuela, Bolivarian Republic of');
insert into gha_countries(code, name) values('vn', 'Viet Nam');
insert into gha_countries(code, name) values('vg', 'Virgin Islands, British');
insert into gha_countries(code, name) values('vi', 'Virgin Islands, U.S.');
insert into gha_countries(code, name) values('wf', 'Wallis and Futuna');
insert into gha_countries(code, name) values('eh', 'Western Sahara');
insert into gha_countries(code, name) values('ye', 'Yemen');
insert into gha_countries(code, name) values('zm', 'Zambia');
insert into gha_countries(code, name) values('zw', 'Zimbabwe');
insert into gha_countries(code, name) values('cs', 'Serbia and Montenegro');
