insert into gha_countries(code, name) values('af', 'Afghanistan') on conflict do nothing;
insert into gha_countries(code, name) values('ax', 'Åland Islands') on conflict do nothing;
insert into gha_countries(code, name) values('al', 'Albania') on conflict do nothing;
insert into gha_countries(code, name) values('dz', 'Algeria') on conflict do nothing;
insert into gha_countries(code, name) values('as', 'American Samoa') on conflict do nothing;
insert into gha_countries(code, name) values('ad', 'Andorra') on conflict do nothing;
insert into gha_countries(code, name) values('ao', 'Angola') on conflict do nothing;
insert into gha_countries(code, name) values('ai', 'Anguilla') on conflict do nothing;
insert into gha_countries(code, name) values('aq', 'Antarctica') on conflict do nothing;
insert into gha_countries(code, name) values('ag', 'Antigua and Barbuda') on conflict do nothing;
insert into gha_countries(code, name) values('ar', 'Argentina') on conflict do nothing;
insert into gha_countries(code, name) values('am', 'Armenia') on conflict do nothing;
insert into gha_countries(code, name) values('aw', 'Aruba') on conflict do nothing;
insert into gha_countries(code, name) values('au', 'Australia') on conflict do nothing;
insert into gha_countries(code, name) values('at', 'Austria') on conflict do nothing;
insert into gha_countries(code, name) values('az', 'Azerbaijan') on conflict do nothing;
insert into gha_countries(code, name) values('bs', 'Bahamas') on conflict do nothing;
insert into gha_countries(code, name) values('bh', 'Bahrain') on conflict do nothing;
insert into gha_countries(code, name) values('bd', 'Bangladesh') on conflict do nothing;
insert into gha_countries(code, name) values('bb', 'Barbados') on conflict do nothing;
insert into gha_countries(code, name) values('by', 'Belarus') on conflict do nothing;
insert into gha_countries(code, name) values('be', 'Belgium') on conflict do nothing;
insert into gha_countries(code, name) values('bz', 'Belize') on conflict do nothing;
insert into gha_countries(code, name) values('bj', 'Benin') on conflict do nothing;
insert into gha_countries(code, name) values('bm', 'Bermuda') on conflict do nothing;
insert into gha_countries(code, name) values('bt', 'Bhutan') on conflict do nothing;
insert into gha_countries(code, name) values('bo', 'Bolivia Plurinational State of') on conflict do nothing;
insert into gha_countries(code, name) values('bq', 'Bonaire Sint Eustatius and Saba') on conflict do nothing;
insert into gha_countries(code, name) values('ba', 'Bosnia and Herzegovina') on conflict do nothing;
insert into gha_countries(code, name) values('bw', 'Botswana') on conflict do nothing;
insert into gha_countries(code, name) values('bv', 'Bouvet Island') on conflict do nothing;
insert into gha_countries(code, name) values('br', 'Brazil') on conflict do nothing;
insert into gha_countries(code, name) values('io', 'British Indian Ocean Territory') on conflict do nothing;
insert into gha_countries(code, name) values('bn', 'Brunei Darussalam') on conflict do nothing;
insert into gha_countries(code, name) values('bg', 'Bulgaria') on conflict do nothing;
insert into gha_countries(code, name) values('bf', 'Burkina Faso') on conflict do nothing;
insert into gha_countries(code, name) values('bi', 'Burundi') on conflict do nothing;
insert into gha_countries(code, name) values('kh', 'Cambodia') on conflict do nothing;
insert into gha_countries(code, name) values('cm', 'Cameroon') on conflict do nothing;
insert into gha_countries(code, name) values('ca', 'Canada') on conflict do nothing;
insert into gha_countries(code, name) values('cv', 'Cape Verde') on conflict do nothing;
insert into gha_countries(code, name) values('ky', 'Cayman Islands') on conflict do nothing;
insert into gha_countries(code, name) values('cf', 'Central African Republic') on conflict do nothing;
insert into gha_countries(code, name) values('td', 'Chad') on conflict do nothing;
insert into gha_countries(code, name) values('cl', 'Chile') on conflict do nothing;
insert into gha_countries(code, name) values('cn', 'China') on conflict do nothing;
insert into gha_countries(code, name) values('cx', 'Christmas Island') on conflict do nothing;
insert into gha_countries(code, name) values('cc', 'Cocos (Keeling) Islands') on conflict do nothing;
insert into gha_countries(code, name) values('co', 'Colombia') on conflict do nothing;
insert into gha_countries(code, name) values('km', 'Comoros') on conflict do nothing;
insert into gha_countries(code, name) values('cg', 'Congo') on conflict do nothing;
insert into gha_countries(code, name) values('cd', 'Congo the Democratic Republic of the') on conflict do nothing;
insert into gha_countries(code, name) values('ck', 'Cook Islands') on conflict do nothing;
insert into gha_countries(code, name) values('cr', 'Costa Rica') on conflict do nothing;
insert into gha_countries(code, name) values('ci', 'Côte Divoire') on conflict do nothing;
insert into gha_countries(code, name) values('hr', 'Croatia') on conflict do nothing;
insert into gha_countries(code, name) values('cu', 'Cuba') on conflict do nothing;
insert into gha_countries(code, name) values('cw', 'Curaçao') on conflict do nothing;
insert into gha_countries(code, name) values('cy', 'Cyprus') on conflict do nothing;
insert into gha_countries(code, name) values('cz', 'Czech Republic') on conflict do nothing;
insert into gha_countries(code, name) values('dk', 'Denmark') on conflict do nothing;
insert into gha_countries(code, name) values('dj', 'Djibouti') on conflict do nothing;
insert into gha_countries(code, name) values('dm', 'Dominica') on conflict do nothing;
insert into gha_countries(code, name) values('do', 'Dominican Republic') on conflict do nothing;
insert into gha_countries(code, name) values('ec', 'Ecuador') on conflict do nothing;
insert into gha_countries(code, name) values('eg', 'Egypt') on conflict do nothing;
insert into gha_countries(code, name) values('sv', 'El Salvador') on conflict do nothing;
insert into gha_countries(code, name) values('gq', 'Equatorial Guinea') on conflict do nothing;
insert into gha_countries(code, name) values('er', 'Eritrea') on conflict do nothing;
insert into gha_countries(code, name) values('ee', 'Estonia') on conflict do nothing;
insert into gha_countries(code, name) values('et', 'Ethiopia') on conflict do nothing;
insert into gha_countries(code, name) values('fk', 'Falkland Islands (Malvinas)') on conflict do nothing;
insert into gha_countries(code, name) values('fo', 'Faroe Islands') on conflict do nothing;
insert into gha_countries(code, name) values('fj', 'Fiji') on conflict do nothing;
insert into gha_countries(code, name) values('fi', 'Finland') on conflict do nothing;
insert into gha_countries(code, name) values('fr', 'France') on conflict do nothing;
insert into gha_countries(code, name) values('gf', 'French Guiana') on conflict do nothing;
insert into gha_countries(code, name) values('pf', 'French Polynesia') on conflict do nothing;
insert into gha_countries(code, name) values('tf', 'French Southern Territories') on conflict do nothing;
insert into gha_countries(code, name) values('ga', 'Gabon') on conflict do nothing;
insert into gha_countries(code, name) values('gm', 'Gambia') on conflict do nothing;
insert into gha_countries(code, name) values('ge', 'Georgia') on conflict do nothing;
insert into gha_countries(code, name) values('de', 'Germany') on conflict do nothing;
insert into gha_countries(code, name) values('gh', 'Ghana') on conflict do nothing;
insert into gha_countries(code, name) values('gi', 'Gibraltar') on conflict do nothing;
insert into gha_countries(code, name) values('gr', 'Greece') on conflict do nothing;
insert into gha_countries(code, name) values('gl', 'Greenland') on conflict do nothing;
insert into gha_countries(code, name) values('gd', 'Grenada') on conflict do nothing;
insert into gha_countries(code, name) values('gp', 'Guadeloupe') on conflict do nothing;
insert into gha_countries(code, name) values('gu', 'Guam') on conflict do nothing;
insert into gha_countries(code, name) values('gt', 'Guatemala') on conflict do nothing;
insert into gha_countries(code, name) values('gg', 'Guernsey') on conflict do nothing;
insert into gha_countries(code, name) values('gn', 'Guinea') on conflict do nothing;
insert into gha_countries(code, name) values('gw', 'Guinea-Bissau') on conflict do nothing;
insert into gha_countries(code, name) values('gy', 'Guyana') on conflict do nothing;
insert into gha_countries(code, name) values('ht', 'Haiti') on conflict do nothing;
insert into gha_countries(code, name) values('hm', 'Heard Island and Mcdonald Islands') on conflict do nothing;
insert into gha_countries(code, name) values('va', 'Holy See (Vatican City State)') on conflict do nothing;
insert into gha_countries(code, name) values('hn', 'Honduras') on conflict do nothing;
insert into gha_countries(code, name) values('hk', 'Hong Kong') on conflict do nothing;
insert into gha_countries(code, name) values('hu', 'Hungary') on conflict do nothing;
insert into gha_countries(code, name) values('is', 'Iceland') on conflict do nothing;
insert into gha_countries(code, name) values('in', 'India') on conflict do nothing;
insert into gha_countries(code, name) values('id', 'Indonesia') on conflict do nothing;
insert into gha_countries(code, name) values('ir', 'Iran Islamic Republic of') on conflict do nothing;
insert into gha_countries(code, name) values('iq', 'Iraq') on conflict do nothing;
insert into gha_countries(code, name) values('ie', 'Ireland') on conflict do nothing;
insert into gha_countries(code, name) values('im', 'Isle of Man') on conflict do nothing;
insert into gha_countries(code, name) values('il', 'Israel') on conflict do nothing;
insert into gha_countries(code, name) values('it', 'Italy') on conflict do nothing;
insert into gha_countries(code, name) values('jm', 'Jamaica') on conflict do nothing;
insert into gha_countries(code, name) values('jp', 'Japan') on conflict do nothing;
insert into gha_countries(code, name) values('je', 'Jersey') on conflict do nothing;
insert into gha_countries(code, name) values('jo', 'Jordan') on conflict do nothing;
insert into gha_countries(code, name) values('kz', 'Kazakhstan') on conflict do nothing;
insert into gha_countries(code, name) values('ke', 'Kenya') on conflict do nothing;
insert into gha_countries(code, name) values('ki', 'Kiribati') on conflict do nothing;
insert into gha_countries(code, name) values('kp', 'Korea Democratic People Republic of') on conflict do nothing;
insert into gha_countries(code, name) values('kr', 'Korea Republic of') on conflict do nothing;
insert into gha_countries(code, name) values('kw', 'Kuwait') on conflict do nothing;
insert into gha_countries(code, name) values('kg', 'Kyrgyzstan') on conflict do nothing;
insert into gha_countries(code, name) values('la', 'Lao People Democratic Republic') on conflict do nothing;
insert into gha_countries(code, name) values('lv', 'Latvia') on conflict do nothing;
insert into gha_countries(code, name) values('lb', 'Lebanon') on conflict do nothing;
insert into gha_countries(code, name) values('ls', 'Lesotho') on conflict do nothing;
insert into gha_countries(code, name) values('lr', 'Liberia') on conflict do nothing;
insert into gha_countries(code, name) values('ly', 'Libya') on conflict do nothing;
insert into gha_countries(code, name) values('li', 'Liechtenstein') on conflict do nothing;
insert into gha_countries(code, name) values('lt', 'Lithuania') on conflict do nothing;
insert into gha_countries(code, name) values('lu', 'Luxembourg') on conflict do nothing;
insert into gha_countries(code, name) values('mo', 'Macao') on conflict do nothing;
insert into gha_countries(code, name) values('mk', 'Macedonia the Former Yugoslav Republic of') on conflict do nothing;
insert into gha_countries(code, name) values('mg', 'Madagascar') on conflict do nothing;
insert into gha_countries(code, name) values('mw', 'Malawi') on conflict do nothing;
insert into gha_countries(code, name) values('my', 'Malaysia') on conflict do nothing;
insert into gha_countries(code, name) values('mv', 'Maldives') on conflict do nothing;
insert into gha_countries(code, name) values('ml', 'Mali') on conflict do nothing;
insert into gha_countries(code, name) values('mt', 'Malta') on conflict do nothing;
insert into gha_countries(code, name) values('mh', 'Marshall Islands') on conflict do nothing;
insert into gha_countries(code, name) values('mq', 'Martinique') on conflict do nothing;
insert into gha_countries(code, name) values('mr', 'Mauritania') on conflict do nothing;
insert into gha_countries(code, name) values('mu', 'Mauritius') on conflict do nothing;
insert into gha_countries(code, name) values('yt', 'Mayotte') on conflict do nothing;
insert into gha_countries(code, name) values('mx', 'Mexico') on conflict do nothing;
insert into gha_countries(code, name) values('fm', 'Micronesia Federated States of') on conflict do nothing;
insert into gha_countries(code, name) values('md', 'Moldova Republic of') on conflict do nothing;
insert into gha_countries(code, name) values('mc', 'Monaco') on conflict do nothing;
insert into gha_countries(code, name) values('mn', 'Mongolia') on conflict do nothing;
insert into gha_countries(code, name) values('me', 'Montenegro') on conflict do nothing;
insert into gha_countries(code, name) values('ms', 'Montserrat') on conflict do nothing;
insert into gha_countries(code, name) values('ma', 'Morocco') on conflict do nothing;
insert into gha_countries(code, name) values('mz', 'Mozambique') on conflict do nothing;
insert into gha_countries(code, name) values('mm', 'Myanmar') on conflict do nothing;
insert into gha_countries(code, name) values('na', 'Namibia') on conflict do nothing;
insert into gha_countries(code, name) values('nr', 'Nauru') on conflict do nothing;
insert into gha_countries(code, name) values('np', 'Nepal') on conflict do nothing;
insert into gha_countries(code, name) values('nl', 'Netherlands') on conflict do nothing;
insert into gha_countries(code, name) values('nc', 'New Caledonia') on conflict do nothing;
insert into gha_countries(code, name) values('nz', 'New Zealand') on conflict do nothing;
insert into gha_countries(code, name) values('ni', 'Nicaragua') on conflict do nothing;
insert into gha_countries(code, name) values('ne', 'Niger') on conflict do nothing;
insert into gha_countries(code, name) values('ng', 'Nigeria') on conflict do nothing;
insert into gha_countries(code, name) values('nu', 'Niue') on conflict do nothing;
insert into gha_countries(code, name) values('nf', 'Norfolk Island') on conflict do nothing;
insert into gha_countries(code, name) values('mp', 'Northern Mariana Islands') on conflict do nothing;
insert into gha_countries(code, name) values('no', 'Norway') on conflict do nothing;
insert into gha_countries(code, name) values('om', 'Oman') on conflict do nothing;
insert into gha_countries(code, name) values('pk', 'Pakistan') on conflict do nothing;
insert into gha_countries(code, name) values('pw', 'Palau') on conflict do nothing;
insert into gha_countries(code, name) values('ps', 'Palestine State of') on conflict do nothing;
insert into gha_countries(code, name) values('pa', 'Panama') on conflict do nothing;
insert into gha_countries(code, name) values('pg', 'Papua New Guinea') on conflict do nothing;
insert into gha_countries(code, name) values('py', 'Paraguay') on conflict do nothing;
insert into gha_countries(code, name) values('pe', 'Peru') on conflict do nothing;
insert into gha_countries(code, name) values('ph', 'Philippines') on conflict do nothing;
insert into gha_countries(code, name) values('pn', 'Pitcairn') on conflict do nothing;
insert into gha_countries(code, name) values('pl', 'Poland') on conflict do nothing;
insert into gha_countries(code, name) values('pt', 'Portugal') on conflict do nothing;
insert into gha_countries(code, name) values('pr', 'Puerto Rico') on conflict do nothing;
insert into gha_countries(code, name) values('qa', 'Qatar') on conflict do nothing;
insert into gha_countries(code, name) values('re', 'Réunion') on conflict do nothing;
insert into gha_countries(code, name) values('ro', 'Romania') on conflict do nothing;
insert into gha_countries(code, name) values('ru', 'Russian Federation') on conflict do nothing;
insert into gha_countries(code, name) values('rw', 'Rwanda') on conflict do nothing;
insert into gha_countries(code, name) values('bl', 'Saint Barthélemy') on conflict do nothing;
insert into gha_countries(code, name) values('sh', 'Saint Helena Ascension and Tristan da Cunha') on conflict do nothing;
insert into gha_countries(code, name) values('kn', 'Saint Kitts and Nevis') on conflict do nothing;
insert into gha_countries(code, name) values('lc', 'Saint Lucia') on conflict do nothing;
insert into gha_countries(code, name) values('mf', 'Saint Martin (French Part)') on conflict do nothing;
insert into gha_countries(code, name) values('pm', 'Saint Pierre and Miquelon') on conflict do nothing;
insert into gha_countries(code, name) values('vc', 'Saint Vincent and the Grenadines') on conflict do nothing;
insert into gha_countries(code, name) values('ws', 'Samoa') on conflict do nothing;
insert into gha_countries(code, name) values('sm', 'San Marino') on conflict do nothing;
insert into gha_countries(code, name) values('st', 'Sao Tome and Principe') on conflict do nothing;
insert into gha_countries(code, name) values('sa', 'Saudi Arabia') on conflict do nothing;
insert into gha_countries(code, name) values('sn', 'Senegal') on conflict do nothing;
insert into gha_countries(code, name) values('rs', 'Serbia') on conflict do nothing;
insert into gha_countries(code, name) values('sc', 'Seychelles') on conflict do nothing;
insert into gha_countries(code, name) values('sl', 'Sierra Leone') on conflict do nothing;
insert into gha_countries(code, name) values('sg', 'Singapore') on conflict do nothing;
insert into gha_countries(code, name) values('sx', 'Sint Maarten (Dutch Part)') on conflict do nothing;
insert into gha_countries(code, name) values('sk', 'Slovakia') on conflict do nothing;
insert into gha_countries(code, name) values('si', 'Slovenia') on conflict do nothing;
insert into gha_countries(code, name) values('sb', 'Solomon Islands') on conflict do nothing;
insert into gha_countries(code, name) values('so', 'Somalia') on conflict do nothing;
insert into gha_countries(code, name) values('za', 'South Africa') on conflict do nothing;
insert into gha_countries(code, name) values('gs', 'South Georgia and the South Sandwich Islands') on conflict do nothing;
insert into gha_countries(code, name) values('ss', 'South Sudan') on conflict do nothing;
insert into gha_countries(code, name) values('es', 'Spain') on conflict do nothing;
insert into gha_countries(code, name) values('lk', 'Sri Lanka') on conflict do nothing;
insert into gha_countries(code, name) values('sd', 'Sudan') on conflict do nothing;
insert into gha_countries(code, name) values('sr', 'Suriname') on conflict do nothing;
insert into gha_countries(code, name) values('sj', 'Svalbard and Jan Mayen') on conflict do nothing;
insert into gha_countries(code, name) values('sz', 'Swaziland') on conflict do nothing;
insert into gha_countries(code, name) values('se', 'Sweden') on conflict do nothing;
insert into gha_countries(code, name) values('ch', 'Switzerland') on conflict do nothing;
insert into gha_countries(code, name) values('sy', 'Syrian Arab Republic') on conflict do nothing;
insert into gha_countries(code, name) values('tw', 'Taiwan Province of China') on conflict do nothing;
insert into gha_countries(code, name) values('tj', 'Tajikistan') on conflict do nothing;
insert into gha_countries(code, name) values('tz', 'Tanzania United Republic of') on conflict do nothing;
insert into gha_countries(code, name) values('th', 'Thailand') on conflict do nothing;
insert into gha_countries(code, name) values('tl', 'Timor-Leste') on conflict do nothing;
insert into gha_countries(code, name) values('tg', 'Togo') on conflict do nothing;
insert into gha_countries(code, name) values('tk', 'Tokelau') on conflict do nothing;
insert into gha_countries(code, name) values('to', 'Tonga') on conflict do nothing;
insert into gha_countries(code, name) values('tt', 'Trinidad and Tobago') on conflict do nothing;
insert into gha_countries(code, name) values('tn', 'Tunisia') on conflict do nothing;
insert into gha_countries(code, name) values('tr', 'Turkey') on conflict do nothing;
insert into gha_countries(code, name) values('tm', 'Turkmenistan') on conflict do nothing;
insert into gha_countries(code, name) values('tc', 'Turks and Caicos Islands') on conflict do nothing;
insert into gha_countries(code, name) values('tv', 'Tuvalu') on conflict do nothing;
insert into gha_countries(code, name) values('ug', 'Uganda') on conflict do nothing;
insert into gha_countries(code, name) values('ua', 'Ukraine') on conflict do nothing;
insert into gha_countries(code, name) values('ae', 'United Arab Emirates') on conflict do nothing;
insert into gha_countries(code, name) values('gb', 'United Kingdom') on conflict do nothing;
insert into gha_countries(code, name) values('us', 'United States') on conflict do nothing;
insert into gha_countries(code, name) values('um', 'United States Minor Outlying Islands') on conflict do nothing;
insert into gha_countries(code, name) values('uy', 'Uruguay') on conflict do nothing;
insert into gha_countries(code, name) values('uz', 'Uzbekistan') on conflict do nothing;
insert into gha_countries(code, name) values('vu', 'Vanuatu') on conflict do nothing;
insert into gha_countries(code, name) values('ve', 'Venezuela Bolivarian Republic of') on conflict do nothing;
insert into gha_countries(code, name) values('vn', 'Viet Nam') on conflict do nothing;
insert into gha_countries(code, name) values('vg', 'Virgin Islands British') on conflict do nothing;
insert into gha_countries(code, name) values('vi', 'Virgin Islands U.S.') on conflict do nothing;
insert into gha_countries(code, name) values('wf', 'Wallis and Futuna') on conflict do nothing;
insert into gha_countries(code, name) values('eh', 'Western Sahara') on conflict do nothing;
insert into gha_countries(code, name) values('ye', 'Yemen') on conflict do nothing;
insert into gha_countries(code, name) values('zm', 'Zambia') on conflict do nothing;
insert into gha_countries(code, name) values('zw', 'Zimbabwe') on conflict do nothing;
insert into gha_countries(code, name) values('cs', 'Serbia and Montenegro') on conflict do nothing;
