grant usage on schema current_state to gha_admin;
grant select on current_state.milestones to gha_admin;
grant select on current_state.issue_labels to gha_admin;
grant select on current_state.prs to gha_admin;
grant select on current_state.issues to gha_admin;
grant usage on schema current_state to devstats_team;
grant select on current_state.milestones to devstats_team;
grant select on current_state.issue_labels to devstats_team;
grant select on current_state.prs to devstats_team;
grant select on current_state.issues to devstats_team;
alter function current_state.label_prefix(some_label text) owner to devstats_team;
alter function current_state.label_suffix(some_label text) owner to devstats_team;
ALTER TABLE current_state.issue_labels OWNER TO devstats_team;
ALTER TABLE current_state.issues OWNER TO devstats_team;
ALTER TABLE current_state.prs OWNER TO devstats_team;
ALTER TABLE current_state.milestones OWNER TO devstats_team;
