select * from org;
update org set name = '{{org}}' where id = 1;
select * from org;
select * from star;
insert into star(id, user_id, dashboard_id) select 1, 1, id from dashboard where uid = {{uid}};
select * from star;
select * from preferences;
insert into preferences(id, org_id, user_id, version, home_dashboard_id, timezone, theme, created, updated) select 1, 1, 1, 0, (select id from dashboard where uid = {{uid}}), '', 'dark', datetime('now'), datetime('now');
insert into preferences(id, org_id, user_id, version, home_dashboard_id, timezone, theme, created, updated) select 2, 1, 0, 0, (select id from dashboard where uid = {{uid}}), '', 'dark', datetime('now'), datetime('now');
select * from preferences;
select * from user;
select id, uid, slug, title from dashboard;
