{
 "title": "Time metrics",
 "tags": [
  "dashboard",
  "vitess"
 ],
 "time": { "from": "now-3y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   { "name": "period", "label": "Period", "query": "d,w,m,q,y" },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "SHOW TAG VALUES WITH KEY = all_repo_group_name"
   },
   {
    "name": "repogroup",
    "query": "SHOW TAG VALUES WITH KEY = all_repo_group_value where all_repo_group_name =~ /^[[repogroup_name]]$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Median time PRs from open to merge (Repository group [[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Time from open to merge.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "Median time from open to merge (in hours)",
     "query": "SELECT \"value\" FROM \"time_metrics_[[repogroup]]_median_open_to_merge_[[period]]\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "85th percentile time PRs from open to merge for (Repository group: [[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Time from open to merge.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "85th percentile time from open to merge (in hours)",
     "query": "SELECT \"value\" FROM \"time_metrics_[[repogroup]]_percentile_85_open_to_merge_[[period]]\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time PRs from open to merge (Repository group[[repogroup_name]], [[period]])",
   "type": "table",
   "description": "Time PRs from open to merge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "Median open to merge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"time_metrics_[[repogroup]]_median_open_to_merge_[[period]]\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "85th percentile open to merge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"time_metrics_[[repogroup]]_percentile_85_open_to_merge_[[period]]\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}