-- generated by github.com/kubevirt/community/hack/generate-devstats-repo-sql.py
-- Add repository groups

update gha_repos set repo_group = 'SIG compute' where name in (
  'kubevirt/ansible-kubevirt-modules',
  'kubevirt/cloud-image-builder',
  'kubevirt/cluster-api-provider-external',
  'kubevirt/common-templates',
  'kubevirt/cpu-nfd-plugin',
  'kubevirt/csi-driver',
  'kubevirt/external-storage',
  'kubevirt/krew-index',
  'kubevirt/kubevirt-ssp-operator',
  'kubevirt/kubevirt-template-validator',
  'kubevirt/kvm-info-nfd-plugin',
  'kubevirt/libvirt',
  'kubevirt/machine-remediation',
  'kubevirt/node-labeller',
  'kubevirt/node-maintenance-operator',
  'kubevirt/ssp-operator'
);

update gha_repos set repo_group = 'SIG virtblocks' where name in (
  'virtblocks/kubevirt'
);

update gha_repos set repo_group = 'SIG network' where name in (
  'k8snetworkplumbingwg/kubemacpool',
  'k8snetworkplumbingwg/multi-networkpolicy-iptables',
  'k8snetworkplumbingwg/sriov-network-operator'
);

-- All other unknown repositories should have 'Other' repository group
-- update gha_repos set repo_group = 'Other' where repo_group is null;

-- By default alias is the newest repo name for given repo ID
update
  gha_repos r
set
  alias = coalesce((
    select e.dup_repo_name
    from
      gha_events e
    where
      e.repo_id = r.id
    order by
      e.created_at desc
    limit 1
  ), name)
;

update gha_repos set alias = 'kubevirt/kubevirt' where name like '%kubevirt' or name = 'kubevirt/';

select
  repo_group,
  count(*) as number_of_repos
from
  gha_repos
where
  repo_group is not null
group by
  repo_group
order by
  number_of_repos desc,
  repo_group asc;

