-- generated by github.com/kubevirt/community/hack/generate-devstats-repo-sql.py
-- Add repository groups

update gha_repos set repo_group = 'SIG compute' where name in (
  'kubevirt/ansible-kubevirt-modules',
  'kubevirt/api-reference',
  'kubevirt/bridge-marker',
  'kubevirt/cdi-api-reference',
  'kubevirt/cdi-operator',
  'kubevirt/client-go',
  'kubevirt/client-python',
  'kubevirt/cloud-image-builder',
  'kubevirt/cloud-provider-kubevirt',
  'kubevirt/cluster-api-provider-external',
  'kubevirt/cluster-network-addons-operator',
  'kubevirt/common-templates',
  'kubevirt/community',
  'kubevirt/controller-lifecycle-operator-sdk',
  'kubevirt/cpu-nfd-plugin',
  'kubevirt/csi-driver',
  'kubevirt/device-plugin-manager',
  'kubevirt/external-storage',
  'kubevirt/gluster-kubernetes',
  'kubevirt/hostpath-provisioner',
  'kubevirt/hostpath-provisioner-operator',
  'kubevirt/hyperconverged-cluster-operator',
  'kubevirt/k8s-start',
  'kubevirt/katacoda-scenarios',
  'kubevirt/krew-index',
  'kubevirt/kubectl-virt-plugin',
  'kubevirt/kubernetes-device-plugins',
  'kubevirt/kubevirt',
  'kubevirt/kubevirt-ansible',
  'kubevirt/kubevirt-operator',
  'kubevirt/kubevirt-ssp-operator',
  'kubevirt/kubevirt-tekton-tasks',
  'kubevirt/kubevirt-template-validator',
  'kubevirt/kvm-info-nfd-plugin',
  'kubevirt/libvirt',
  'kubevirt/machine-remediation',
  'kubevirt/macvtap-cni',
  'kubevirt/manageiq-providers-kubevirt',
  'kubevirt/must-gather',
  'kubevirt/node-labeller',
  'kubevirt/node-maintenance-operator',
  'kubevirt/ovs-cni',
  'kubevirt/qe-tools',
  'kubevirt/run',
  'kubevirt/secrets',
  'kubevirt/ssp-operator',
  'kubevirt/storage-demo',
  'kubevirt/test-infra-containers',
  'kubevirt/v2v-job',
  'kubevirt/vAdvisor',
  'kubevirt/vm-import-operator',
  'kubevirt/vmctl'
);

update gha_repos set repo_group = 'SIG documentation' where name in (
  'kubevirt/blog',
  'kubevirt/cockpit-demo',
  'kubevirt/demo',
  'kubevirt/kubevirt-tutorial',
  'kubevirt/kubevirt.github.io',
  'kubevirt/user-guide'
);

update gha_repos set repo_group = 'SIG storage' where name in (
  'kubevirt/containerized-data-importer'
);

update gha_repos set repo_group = 'SIG testing' where name in (
  'kubevirt/kubevirtci',
  'kubevirt/project-infra'
);

update gha_repos set repo_group = 'SIG virtctl' where name in (
  'kubevirt/kubectl-virt-plugin'
);

update gha_repos set repo_group = 'SIG virtblocks' where name in (
  'virtblocks/closefds',
  'virtblocks/kubevirt',
  'virtblocks/libvirt',
  'virtblocks/virtblocks'
);

update gha_repos set repo_group = 'SIG network' where name in (
  'k8snetworkplumbingwg/community',
  'k8snetworkplumbingwg/device-info-spec',
  'k8snetworkplumbingwg/helm-charts',
  'k8snetworkplumbingwg/k8s-net-attach-def-controller',
  'k8snetworkplumbingwg/kubemacpool',
  'k8snetworkplumbingwg/multi-net-spec',
  'k8snetworkplumbingwg/multi-networkpolicy',
  'k8snetworkplumbingwg/multi-networkpolicy-iptables',
  'k8snetworkplumbingwg/net-attach-def-admission-controller',
  'k8snetworkplumbingwg/net-service-controller',
  'k8snetworkplumbingwg/network-attachment-definition-client',
  'k8snetworkplumbingwg/network-resources-injector',
  'k8snetworkplumbingwg/reference-deployment',
  'k8snetworkplumbingwg/sriov-cni',
  'k8snetworkplumbingwg/sriov-network-device-plugin',
  'k8snetworkplumbingwg/sriov-network-operator',
  'k8snetworkplumbingwg/toc',
  'nmstate/ansible-nmstate',
  'nmstate/kubernetes-nmstate',
  'nmstate/nmstate',
  'nmstate/nmstate.github.io'
);

update gha_repos set repo_group = 'SIG userinterface' where name in (
  'kubevirt/cockpit',
  'kubevirt/origin-web-console',
  'kubevirt/origin-web-console-server',
  'kubevirt/web-ui',
  'kubevirt/web-ui-components',
  'kubevirt/web-ui-design',
  'kubevirt/web-ui-operator'
);

-- All other unknown repositories should have 'Other' repository group
-- update gha_repos set repo_group = 'Other' where repo_group is null;

-- By default alias is the newest repo name for given repo ID
update
  gha_repos r
set
  alias = coalesce((
    select e.dup_repo_name
    from
      gha_events e
    where
      e.repo_id = r.id
    order by
      e.created_at desc
    limit 1
  ), name)
;

update gha_repos set alias = 'kubevirt/kubevirt' where name like '%kubevirt' or name = 'kubevirt/';

select
  repo_group,
  count(*) as number_of_repos
from
  gha_repos
where
  repo_group is not null
group by
  repo_group
order by
  number_of_repos desc,
  repo_group asc;

