{{- $skipSecrets := .Values.skipSecrets -}}
{{ if not $skipSecrets }}
{{- $skipSHSecret := .Values.skipSHSecret -}}
{{ if not $skipSHSecret }}
# SH secret starts
{{- $shUser := or .Values.shUser (.Files.Get "secrets/SH_USER.secret") -}}
{{- $shHost := or .Values.shHost (.Files.Get "secrets/SH_HOST.secret") -}}
{{- $shPort := or .Values.shPort (.Files.Get "secrets/SH_PORT.secret") -}}
{{- $shPass := or .Values.shPass (.Files.Get "secrets/SH_PASS.secret") -}}
{{- $shDB := or .Values.shDB (.Files.Get "secrets/SH_DB.secret") -}}
{{ if and $shUser $shHost $shPort $shPass $shDB }}
---
apiVersion: v1
data:
  SH_USER.secret: {{ $shUser | b64enc }}
  SH_HOST.secret: {{ $shHost | b64enc }}
  SH_PORT.secret: {{ $shPort | b64enc }}
  SH_PASS.secret: {{ $shPass | b64enc }}
  SH_DB.secret: {{ $shDB | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.shSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "json2hat-helm.name" . }}
    helm.sh/chart: {{ include "json2hat-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_one_or_more_sh_secrets: "Please take a look at the NOTES.txt file"
{{ end }}
# SH secret ends
{{ end }}
{{ end }}
