#!/bin/sh
# This script assumes that You have cncf/artwork cloned in ~/dev/cncf/artwork 
cp ~/dev/cncf/artwork/kubernetes/icon/color/kubernetes-icon-color.svg /usr/share/grafana.k8s/public/img/grafana_icon.svg || exit 1
cp ~/dev/cncf/artwork/kubernetes/icon/color/kubernetes-icon-color.svg /usr/share/grafana.k8s/public/img/grafana_com_auth_icon.svg || exit 2
cp ~/dev/cncf/artwork/kubernetes/icon/color/kubernetes-icon-color.svg /usr/share/grafana.k8s/public/img/grafana_net_logo.svg || exit 3
cp ~/dev/cncf/artwork/kubernetes/icon/color/kubernetes-icon-color.svg /usr/share/grafana.k8s/public/img/grafana_mask_icon.svg || exit 4
cp ~/dev/cncf/artwork/prometheus/icon/color/prometheus-icon-color.svg /usr/share/grafana.prometheus/public/img/grafana_icon.svg || exit 5
cp ~/dev/cncf/artwork/prometheus/icon/color/prometheus-icon-color.svg /usr/share/grafana.prometheus/public/img/grafana_com_auth_icon.svg || exit 6
cp ~/dev/cncf/artwork/prometheus/icon/color/prometheus-icon-color.svg /usr/share/grafana.prometheus/public/img/grafana_net_logo.svg || exit 7
cp ~/dev/cncf/artwork/prometheus/icon/color/prometheus-icon-color.svg /usr/share/grafana.prometheus/public/img/grafana_mask_icon.svg || exit 8
cp ~/dev/cncf/artwork/opentracing/icon/color/opentracing-icon-color.svg /usr/share/grafana.opentracing/public/img/grafana_icon.svg || exit 9
cp ~/dev/cncf/artwork/opentracing/icon/color/opentracing-icon-color.svg /usr/share/grafana.opentracing/public/img/grafana_com_auth_icon.svg || exit 10
cp ~/dev/cncf/artwork/opentracing/icon/color/opentracing-icon-color.svg /usr/share/grafana.opentracing/public/img/grafana_net_logo.svg || exit 11
cp ~/dev/cncf/artwork/opentracing/icon/color/opentracing-icon-color.svg /usr/share/grafana.opentracing/public/img/grafana_mask_icon.svg || exit 12
cp ~/dev/cncf/artwork/fluentd/icon/color/fluentd-icon-color.svg /usr/share/grafana.fluentd/public/img/grafana_icon.svg || exit 13
cp ~/dev/cncf/artwork/fluentd/icon/color/fluentd-icon-color.svg /usr/share/grafana.fluentd/public/img/grafana_com_auth_icon.svg || exit 14
cp ~/dev/cncf/artwork/fluentd/icon/color/fluentd-icon-color.svg /usr/share/grafana.fluentd/public/img/grafana_net_logo.svg || exit 15
cp ~/dev/cncf/artwork/fluentd/icon/color/fluentd-icon-color.svg /usr/share/grafana.fluentd/public/img/grafana_mask_icon.svg || exit 16
cp ~/dev/cncf/artwork/linkerd/icon/color/linkerd-icon-color.svg /usr/share/grafana.linkerd/public/img/grafana_icon.svg || exit 17
cp ~/dev/cncf/artwork/linkerd/icon/color/linkerd-icon-color.svg /usr/share/grafana.linkerd/public/img/grafana_com_auth_icon.svg || exit 18
cp ~/dev/cncf/artwork/linkerd/icon/color/linkerd-icon-color.svg /usr/share/grafana.linkerd/public/img/grafana_net_logo.svg || exit 19
cp ~/dev/cncf/artwork/linkerd/icon/color/linkerd-icon-color.svg /usr/share/grafana.linkerd/public/img/grafana_mask_icon.svg || exit 20
cp ~/dev/cncf/artwork/grpc/icon/color/grpc-icon-color.svg /usr/share/grafana.grpc/public/img/grafana_icon.svg || exit 21
cp ~/dev/cncf/artwork/grpc/icon/color/grpc-icon-color.svg /usr/share/grafana.grpc/public/img/grafana_com_auth_icon.svg || exit 22
cp ~/dev/cncf/artwork/grpc/icon/color/grpc-icon-color.svg /usr/share/grafana.grpc/public/img/grafana_net_logo.svg || exit 23
cp ~/dev/cncf/artwork/grpc/icon/color/grpc-icon-color.svg /usr/share/grafana.grpc/public/img/grafana_mask_icon.svg || exit 24
cp ~/dev/cncf/artwork/coredns/icon/color/coredns-icon-color.svg /usr/share/grafana.coredns/public/img/grafana_icon.svg || exit 25
cp ~/dev/cncf/artwork/coredns/icon/color/coredns-icon-color.svg /usr/share/grafana.coredns/public/img/grafana_com_auth_icon.svg || exit 26
cp ~/dev/cncf/artwork/coredns/icon/color/coredns-icon-color.svg /usr/share/grafana.coredns/public/img/grafana_net_logo.svg || exit 27
cp ~/dev/cncf/artwork/coredns/icon/color/coredns-icon-color.svg /usr/share/grafana.coredns/public/img/grafana_mask_icon.svg || exit 28
cp ~/dev/cncf/artwork/containerd/icon/white/containerd-icon-white.svg /usr/share/grafana.containerd/public/img/grafana_icon.svg || exit 29
cp ~/dev/cncf/artwork/containerd/icon/white/containerd-icon-white.svg /usr/share/grafana.containerd/public/img/grafana_com_auth_icon.svg || exit 30
cp ~/dev/cncf/artwork/containerd/icon/white/containerd-icon-white.svg /usr/share/grafana.containerd/public/img/grafana_net_logo.svg || exit 31
cp ~/dev/cncf/artwork/containerd/icon/white/containerd-icon-white.svg /usr/share/grafana.containerd/public/img/grafana_mask_icon.svg || exit 32
cp ~/dev/cncf/artwork/rkt/icon/color/rkt-icon-color.svg /usr/share/grafana.rkt/public/img/grafana_icon.svg || exit 33
cp ~/dev/cncf/artwork/rkt/icon/color/rkt-icon-color.svg /usr/share/grafana.rkt/public/img/grafana_com_auth_icon.svg || exit 34
cp ~/dev/cncf/artwork/rkt/icon/color/rkt-icon-color.svg /usr/share/grafana.rkt/public/img/grafana_net_logo.svg || exit 35
cp ~/dev/cncf/artwork/rkt/icon/color/rkt-icon-color.svg /usr/share/grafana.rkt/public/img/grafana_mask_icon.svg || exit 36
cp ~/dev/cncf/artwork/cni/icon/color/cni-icon-color.svg /usr/share/grafana.cni/public/img/grafana_icon.svg || exit 37
cp ~/dev/cncf/artwork/cni/icon/color/cni-icon-color.svg /usr/share/grafana.cni/public/img/grafana_com_auth_icon.svg || exit 38
cp ~/dev/cncf/artwork/cni/icon/color/cni-icon-color.svg /usr/share/grafana.cni/public/img/grafana_net_logo.svg || exit 39
cp ~/dev/cncf/artwork/cni/icon/color/cni-icon-color.svg /usr/share/grafana.cni/public/img/grafana_mask_icon.svg || exit 40
cp ~/dev/cncf/artwork/envoy/icon/color/envoy-icon-color.svg /usr/share/grafana.envoy/public/img/grafana_icon.svg || exit 41
cp ~/dev/cncf/artwork/envoy/icon/color/envoy-icon-color.svg /usr/share/grafana.envoy/public/img/grafana_com_auth_icon.svg || exit 42
cp ~/dev/cncf/artwork/envoy/icon/color/envoy-icon-color.svg /usr/share/grafana.envoy/public/img/grafana_net_logo.svg || exit 43
cp ~/dev/cncf/artwork/envoy/icon/color/envoy-icon-color.svg /usr/share/grafana.envoy/public/img/grafana_mask_icon.svg || exit 44
cp ~/dev/cncf/artwork/jaeger/icon/reverse-color/jaeger-icon-reverse-color.svg /usr/share/grafana.jaeger/public/img/grafana_icon.svg || exit 45
cp ~/dev/cncf/artwork/jaeger/icon/reverse-color/jaeger-icon-reverse-color.svg /usr/share/grafana.jaeger/public/img/grafana_com_auth_icon.svg || exit 46
cp ~/dev/cncf/artwork/jaeger/icon/reverse-color/jaeger-icon-reverse-color.svg /usr/share/grafana.jaeger/public/img/grafana_net_logo.svg || exit 47
cp ~/dev/cncf/artwork/jaeger/icon/reverse-color/jaeger-icon-reverse-color.svg /usr/share/grafana.jaeger/public/img/grafana_mask_icon.svg || exit 48
cp ~/dev/cncf/artwork/notary/icon/white/notary-icon-white.svg /usr/share/grafana.notary/public/img/grafana_icon.svg || exit 49
cp ~/dev/cncf/artwork/notary/icon/white/notary-icon-white.svg /usr/share/grafana.notary/public/img/grafana_com_auth_icon.svg || exit 50
cp ~/dev/cncf/artwork/notary/icon/white/notary-icon-white.svg /usr/share/grafana.notary/public/img/grafana_net_logo.svg || exit 51
cp ~/dev/cncf/artwork/notary/icon/white/notary-icon-white.svg /usr/share/grafana.notary/public/img/grafana_mask_icon.svg || exit 52
cp ~/dev/cncf/artwork/tuf/icon/white/tuf-icon-white.svg /usr/share/grafana.tuf/public/img/grafana_icon.svg || exit 53
cp ~/dev/cncf/artwork/tuf/icon/white/tuf-icon-white.svg /usr/share/grafana.tuf/public/img/grafana_com_auth_icon.svg || exit 54
cp ~/dev/cncf/artwork/tuf/icon/white/tuf-icon-white.svg /usr/share/grafana.tuf/public/img/grafana_net_logo.svg || exit 55
cp ~/dev/cncf/artwork/tuf/icon/white/tuf-icon-white.svg /usr/share/grafana.tuf/public/img/grafana_mask_icon.svg || exit 56
cp ~/dev/cncf/artwork/rook/icon/color/rook-icon-color.svg /usr/share/grafana.rook/public/img/grafana_icon.svg || exit 57
cp ~/dev/cncf/artwork/rook/icon/color/rook-icon-color.svg /usr/share/grafana.rook/public/img/grafana_com_auth_icon.svg || exit 58
cp ~/dev/cncf/artwork/rook/icon/color/rook-icon-color.svg /usr/share/grafana.rook/public/img/grafana_net_logo.svg || exit 59
cp ~/dev/cncf/artwork/rook/icon/color/rook-icon-color.svg /usr/share/grafana.rook/public/img/grafana_mask_icon.svg || exit 60
cp ~/dev/cncf/artwork/vitess/icon/color/vitess-icon-color.svg /usr/share/grafana.vitess/public/img/grafana_icon.svg || exit 61
cp ~/dev/cncf/artwork/vitess/icon/color/vitess-icon-color.svg /usr/share/grafana.vitess/public/img/grafana_com_auth_icon.svg || exit 62
cp ~/dev/cncf/artwork/vitess/icon/color/vitess-icon-color.svg /usr/share/grafana.vitess/public/img/grafana_net_logo.svg || exit 63
cp ~/dev/cncf/artwork/vitess/icon/color/vitess-icon-color.svg /usr/share/grafana.vitess/public/img/grafana_mask_icon.svg || exit 64
host=`hostname`
if [ $host = "cncftest.io" ]
then
  cp ~/dev/cncf/artwork/cncf/icon/color/cncf-icon-color.svg /usr/share/grafana.all/public/img/grafana_icon.svg || exit 65
  cp ~/dev/cncf/artwork/cncf/icon/color/cncf-icon-color.svg /usr/share/grafana.all/public/img/grafana_com_auth_icon.svg || exit 66
  cp ~/dev/cncf/artwork/cncf/icon/color/cncf-icon-color.svg /usr/share/grafana.all/public/img/grafana_net_logo.svg || exit 67
  cp ~/dev/cncf/artwork/cncf/icon/color/cncf-icon-color.svg /usr/share/grafana.all/public/img/grafana_mask_icon.svg || exit 68
  cp ~/dev/cncf/artwork/cncf/icon/color/cncf-icon-color.svg /usr/share/grafana.cncf/public/img/grafana_icon.svg || exit 69
  cp ~/dev/cncf/artwork/cncf/icon/color/cncf-icon-color.svg /usr/share/grafana.cncf/public/img/grafana_com_auth_icon.svg || exit 70
  cp ~/dev/cncf/artwork/cncf/icon/color/cncf-icon-color.svg /usr/share/grafana.cncf/public/img/grafana_net_logo.svg || exit 71
  cp ~/dev/cncf/artwork/cncf/icon/color/cncf-icon-color.svg /usr/share/grafana.cncf/public/img/grafana_mask_icon.svg || exit 72
fi
echo 'OK'
