#!/bin/bash
cp stub.md activity.md
cp stub.md commits.md
cp stub.md community_stats.md
cp stub.md companies_stats.md
cp stub.md companies_summary.md
cp stub.md contributing_companies.md
cp stub.md dashboards.md
cp stub.md developers_summary.md
cp stub.md non_author_activity.md
cp stub.md issues_age.md
cp stub.md issues.md
cp stub.md new_contributors.md
cp stub.md new_issues.md
cp stub.md new_prs.md
cp stub.md opened_to_merged.md
cp stub.md pr_comments.md
cp stub.md projects_stats.md
cp stub.md prs_age.md
cp stub.md prs_approval.md
cp stub.md pr_companies.md
cp stub.md pr_authors.md
cp stub.md prs_authors_chart.md
cp stub.md prs_merged.md
cp stub.md repo_commenters.md
cp stub.md repo_comments.md
cp stub.md time_metrics.md
cp stub.md top_commenters.md
cp stub.md user_reviews.md
cp stub.md dashboards.md
