#!/bin/bash
#REPO="kubernetes/kubernetes" FROM="date1" TO="date2" GHA2DB_LOCAL=1 GHA2DB_SKIPPDB=1 GHA2DB_RECENT_RANGE="3 hour" GHA2DB_RECENT_REPOS_RANGE="3 hour" PG_DB=gha ./ghapi2db
GHA2DB_LOCAL=1 GHA2DB_SKIPPDB=1 GHA2DB_RECENT_RANGE="3 hour" GHA2DB_RECENT_REPOS_RANGE="3 hour" PG_DB=gha ./ghapi2db
