#!/bin/bash
# ONLY=cncf SKIPTEMP=1 GHA2DB_PROJECTS_OVERRIDE="+cncf" GHA2DB_USE_ES=1 GHA2DB_USE_ES_ONLY=1 GHA2DB_SKIPTSDB=1 GHA2DB_SKIPPDB=1 GHA2DB_LOCAL=1 ./devel/reinit.sh
ONLY=cncf SKIPTEMP=1 GHA2DB_PROJECTS_OVERRIDE="+cncf" GHA2DB_USE_ES=1 GHA2DB_LOCAL=1 ./devel/reinit.sh
