#!/bin/bash
MODE=ss0 FROM=CNI TO='[[full_name]]' FILES=`find grafana/dashboards/cni/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/cni/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM='containerd ' TO='[[full_name]] ' FILES=`find grafana/dashboards/containerd/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/containerd/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=CoreDNS TO='[[full_name]]' FILES=`find grafana/dashboards/coredns/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/coredns/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=Envoy TO='[[full_name]]' FILES=`find grafana/dashboards/envoy/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/envoy/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=Fluentd TO='[[full_name]]' FILES=`find grafana/dashboards/fluentd/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/fluentd/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=gRPC TO='[[full_name]]' FILES=`find grafana/dashboards/grpc/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/grpc/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=Jaeger TO='[[full_name]]' FILES=`find grafana/dashboards/jaeger/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/jaeger/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=Linkerd TO='[[full_name]]' FILES=`find grafana/dashboards/linkerd/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/linkerd/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=Notary TO='[[full_name]]' FILES=`find grafana/dashboards/notary/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/notary/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=OCI TO='[[full_name]]' FILES=`find grafana/dashboards/opencontainers/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/opencontainers/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=OpenTracing TO='[[full_name]]' FILES=`find grafana/dashboards/opentracing/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/opentracing/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM='rkt ' TO='[[full_name]] ' FILES=`find grafana/dashboards/rkt/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/rkt/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=Rook TO='[[full_name]]' FILES=`find grafana/dashboards/rook/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/rook/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=TUF TO='[[full_name]]' FILES=`find grafana/dashboards/tuf/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/tuf/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=Vitess TO='[[full_name]]' FILES=`find grafana/dashboards/vitess/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/vitess/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=Kubernetes TO='[[full_name]]' FILES=`find grafana/dashboards/kubernetes/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/kubernetes/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM=Prometheus TO='[[full_name]]' FILES=`find grafana/dashboards/prometheus/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/prometheus/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
MODE=ss0 FROM='All CNCF' TO='[[full_name]]' FILES=`find grafana/dashboards/all/ -type f -not -iname dashboards.json` ./devel/mass_replace.sh
MODE=ss FROM='      "title": "' TO='      "title": "[[full_name]] ' FILES=`find grafana/dashboards/all/ -name "top_commenters.json" -or -name "project_statistics.json" -or -name "companies_summary.json" -or -name "prs_authors_companies_histogram.json" -or -name "developers_summary.json" -or -name "prs_authors_histogram.json"` ./devel/mass_replace.sh
