{
 "title": "Awaiting PRs by SIG",
 "tags": [
  "dashboard",
  "kubernetes",
  "SIGs",
  "PRs"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sigs",
    "label": "SIG",
    "query": "select '\"' || sig_mentions_labels_name || '\"' from tsig_mentions_labels order by 1"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'awaiting_prs_by_sig_docs_html'"
   }
  ]
 },
 "panels": [
  {
   "title": "Awaiting PRs by SIG (open for 90 days or more)",
   "type": "graph",
   "description": "PRs by SIG that were open for 90 or more days at s given point in time",
   "gridPos": { "w": 24, "x": 0, "y": 0, "h": 21 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter",
     "measurement": "notused",
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  sawaiting_prs_by_sigd90\nwhere\n  $__timeFilter(time)\n  and period = 'd'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Awaiting PRs by SIG (open for 60 days or more)",
   "type": "graph",
   "description": "PRs by SIG that were open for 60 or more days at s given point in time",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  sawaiting_prs_by_sigd60\nwhere\n  $__timeFilter(time)\n  and period = 'd'\norder by\n  time",
     "measurement": "notused"
    }
   ]
  },
  {
   "title": "Awaiting PRs by SIG (open for 30 days or more)",
   "type": "graph",
   "description": "PRs by SIG that were open for 30 or more days at s given point in time",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "notused",
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  sawaiting_prs_by_sigd30\nwhere\n  $__timeFilter(time)\n  and period = 'd'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Awaiting PRs by SIG (open for 10 days or more)",
   "type": "graph",
   "description": "PRs by SIG that were open for 10 or more days at s given point in time",
   "gridPos": { "w": 24, "x": 0, "y": 63, "h": 21 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  sawaiting_prs_by_sigd10\nwhere\n  $__timeFilter(time)\n  and period = 'd'\norder by\n  time",
     "measurement": "notused",
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Stalled PRs by SIG (open for 1 year or more)",
   "type": "graph",
   "description": "Stalled PRs by SIG that were open for 1 year or more days at s given point in time",
   "gridPos": { "y": 84, "h": 21, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "notused",
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  sawaiting_prs_by_sigy\nwhere\n  $__timeFilter(time)\n  and period = 'd'\norder by\n  time",
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter"
    }
   ]
  },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 105 }, "content": "${docs:raw}" }
 ]
}