{
 "title": "Inactive Issues by SIG",
 "tags": [
  "SIGs",
  "issues",
  "kubernetes",
  "dashboard"
 ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sigs",
    "label": "SIG",
    "query": "select '\"' || sig_mentions_labels_name || '\"' from tsig_mentions_labels order by 1"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'inactive_issues_by_sig_docs_html'"
   }
  ]
 },
 "panels": [
  {
   "title": "Inactive Issues by SIG (inactive for 90 days or more)",
   "type": "graph",
   "description": "Issues by SIG that were inactive for 90 or more days at s given point in time",
   "gridPos": { "w": 24, "x": 0, "y": 0, "h": 21 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  sinactive_issues_by_sigd90\nwhere\n  $__timeFilter(time)\n  and period = 'd'\norder by\n  time",
     "measurement": "notused",
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Inactive Issues by SIG (inactive for 30 days or more)",
   "type": "graph",
   "description": "Issues by SIG that were inactive for 30 or more days at s given point in time",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  sinactive_issues_by_sigd30\nwhere\n  $__timeFilter(time)\n  and period = 'd'\norder by\n  time",
     "measurement": "notused",
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Inactive Issues by SIG (inactive for 2 weeks or more)",
   "type": "graph",
   "description": "Issues by SIG that were inactive for 2 or more weeks at s given point in time",
   "gridPos": { "y": 42, "h": 21, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter",
     "measurement": "notused",
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  sinactive_issues_by_sigw2\nwhere\n  $__timeFilter(time)\n  and period = 'd'\norder by\n  time"
    }
   ]
  },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "y": 63, "h": 10, "w": 24, "x": 0 }, "content": "${docs:raw}" }
 ]
}