{
 "title": "Inactive Issues by SIG and repository",
 "tags": [
  "SIGs",
  "issues",
  "kubernetes",
  "dashboard",
  "repos"
 ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sigs",
    "label": "SIG",
    "query": "select '\"' || sig_mentions_labels_name || '\"' from tsig_mentions_labels order by 1"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'inactive_issues_by_sig_docs_html'"
   },
   {
    "name": "repo_name",
    "label": "Repository",
    "query": "select repo_name from trepos order by 1"
   },
   {
    "name": "repo",
    "query": "select repo_value from trepos where repo_name = '[[repo_name]]'"
   }
  ]
 },
 "panels": [
  {
   "title": "Inactive Issues by SIG for [[repo_name]] repository (inactive for 90 days or more)",
   "type": "graph",
   "description": "Issues by SIG that were inactive for 90 or more days at s given point in time",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "notused",
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  sinactive_issues_by_sig_repos\nwhere\n  $__timeFilter(time)\n  and period = 'd'\n  and series = 'inactive_issues_by_sig_repos[[repo]]d90'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Inactive Issues by SIG for [[repo_name]] repository (inactive for 30 days or more)",
   "type": "graph",
   "description": "Issues by SIG that were inactive for 30 or more days at s given point in time",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "notused",
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  sinactive_issues_by_sig_repos\nwhere\n  $__timeFilter(time)\n  and period = 'd'\n  and series = 'inactive_issues_by_sig_repos[[repo]]d30'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Inactive Issues by SIG for [[repo_name]] repository (inactive for 2 weeks or more)",
   "type": "graph",
   "description": "Issues by SIG that were inactive for 2 or more weeks at s given point in time",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "notused",
     "query": "SELECT /^[[sigs]]$/ FROM \"sig_pr_workload_absolute_workload_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  ${sigs:csv}\nfrom\n  sinactive_issues_by_sig_repos\nwhere\n  $__timeFilter(time)\n  and period = 'd'\n  and series = 'inactive_issues_by_sig_repos[[repo]]w2'\norder by\n  time"
    }
   ]
  },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 63 }, "options": { "content": "${docs:raw}" } }
 ]
}