{
 "title": "PR Time to Engagement",
 "tags": [
  "dashboard",
  "kubernetes",
  "repogroups",
  "PRs",
  "repos"
 ],
 "time": { "from": "now-2y", "to": "now-2w" },
 "templating": {
  "list": [
   { "name": "period", "label": "Period", "query": "d7,w,m,q,y" },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "select all_repo_group_name from tall_repo_groups order by 1"
   },
   {
    "name": "repo_name",
    "label": "Repository",
    "query": "select repo_name from trepos order by 1"
   },
   {
    "name": "repogroup",
    "query": "select all_repo_group_value from tall_repo_groups where all_repo_group_name = '[[repogroup_name]]'"
   },
   {
    "name": "repo",
    "query": "select repo_value from trepos where repo_name = '[[repo_name]]'"
   },
   {
    "name": "kind_name",
    "label": "Kind",
    "query": "select sigm_lbl_kind_name_with_all from tsigm_lbl_kinds_with_all where sigm_lbl_kind_name_with_all in ('All', 'api-change', 'bug', 'feature', 'design', 'cleanup', 'documentation', 'flake', 'kep') order by 1;"
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": "select sigm_lbl_kind_value_with_all from tsigm_lbl_kinds_with_all where sigm_lbl_kind_name_with_all = '[[kind_name]]'"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'pr_time_to_engagement_docs_html'"
   }
  ]
 },
 "panels": [
  {
   "title": "Time before any comments or activities from someone other than the author (repo group: [[repogroup_name]], kind: [[kind_name]], [[period]])",
   "type": "graph",
   "description": "Time before any comments or activities from someone other than the author",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"85th percentile time\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]][[kind]]p85'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]][[kind]]med'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"15th percentile time\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]][[kind]]p15'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Time to first non-author activity (repo group: [[repogroup_name]], kind: [[kind]], [[period]])",
   "type": "table-old",
   "description": "Time to first non-author activity",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"15th percentile\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]][[kind]]p15'\norder by\n  time"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"Median\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]][[kind]]med'\norder by\n  time"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"85th percentile\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]][[kind]]p85'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Time before any comments or activities from someone other than the author (repo: [[repo_name]], kind: [[kind_name]], [[period]])",
   "type": "graph",
   "description": "Time before any comments or activities from someone other than the author",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"85th percentile time\"\nfrom\n  sfirst_non_author_repos\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repo]][[kind]]p85'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time\"\nfrom\n  sfirst_non_author_repos\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repo]][[kind]]med'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"15th percentile time\"\nfrom\n  sfirst_non_author_repos\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repo]][[kind]]p15'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Time to first non-author activity (repo: [[repo_name]], kind: [[kind]], [[period]])",
   "type": "table-old",
   "description": "Time to first non-author activity",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"15th percentile\"\nfrom\n  sfirst_non_author_repos\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repo]][[kind]]p15'\norder by\n  time"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"Median\"\nfrom\n  sfirst_non_author_repos\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repo]][[kind]]med'\norder by\n  time"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"85th percentile\"\nfrom\n  sfirst_non_author_repos\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repo]][[kind]]p85'\norder by\n  time"
    }
   ]
  },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 }, "options": { "content": "${docs:raw}" } }
 ]
}