{
 "title": "PRs labels by SIG",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sig_name",
    "label": "SIG",
    "query": "select case sig_mentions_labels_name_with_all when 'All' then 'All SIGs combined' else sig_mentions_labels_name_with_all end from tsig_mentions_labels_with_all order by 1"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   {
    "name": "label_name",
    "label": "Label",
    "query": "select pr_labels_tags_name from tpr_labels_tags order by 1"
   },
   {
    "name": "sig",
    "label": "SIG",
    "query": "select case sig_mentions_labels_value_with_all when 'all' then 'allsigscombined' else sig_mentions_labels_value_with_all  end from tsig_mentions_labels_with_all where sig_mentions_labels_name_with_all = case '[[sig_name]]' when 'All SIGs combined' then 'All' else '[[sig_name]]' end"
   },
   {
    "name": "label",
    "query": "select pr_labels_tags_value from tpr_labels_tags where pr_labels_tags_name = '[[label_name]]'"
   },
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'prs_labels_by_sig_docs_html'"
   }
  ]
 },
 "panels": [
  {
   "title": "PRs from [[sig_name]] with [[label_name]]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select /^[[repogroups]]: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value\nfrom\n  sprs_labels_by_sig\nwhere\n  $__timeFilter(time)\n  and series = 'prsiglbl[[sig]][[label]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs from [[sig_name]] with [[label_name]]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select /^[[repogroups]]: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value\nfrom\n  sprs_labels_by_sig\nwhere\n  $__timeFilter(time)\n  and series = 'prsiglbl[[sig]][[label]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs from [[sig_name]] with [[label_name]]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /^[[repogroups]]: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"[[sig_name]]: [[label_name]]\"\nfrom\n  sprs_labels_by_sig\nwhere\n  $__timeFilter(time)\n  and series = 'prsiglbl[[sig]][[label]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs with [[label_name]] labels from all SIGs",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "with series as (\n  select distinct l.time as time,\n    r.sig_mentions_labels_name_with_all as metric_name,\n    r.sig_mentions_labels_value_with_all as metric_value\n  from\n    sprs_labels_by_sig l,\n    tsig_mentions_labels_with_all r\n  where\n    $__timeFilter(l.time)\n    and r.sig_mentions_labels_name_with_all != 'All'\n)\nselect\n  s.time as time,\n  s.metric_name as metric,\n  coalesce(l.value, 0) as value\nfrom\n  series s\nleft join\n  sprs_labels_by_sig l\non\n  l.series = 'prsiglbl' || s.metric_value || '[[label]]'                     \n  and l.time = s.time\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs from [[sig_name]] (having at least one of specified labels)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /^[[repogroups]]: / FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "with series as (\n  select distinct l.time as time,\n    lt.pr_labels_tags_name as metric_name,\n    lt.pr_labels_tags_value as metric_value\n  from\n    sprs_labels_by_sig l,\n    tpr_labels_tags lt\n  where\n    $__timeFilter(l.time)\n    and lt.pr_labels_tags_name != 'All labels combined'\n)\nselect\n  s.time as time,\n  s.metric_name as metric,\n  coalesce(l.value, 0) as value\nfrom\n  series s\nleft join\n  sprs_labels_by_sig l\non\n  l.series = 'prsiglbl[[sig]]' || s.metric_value           \n  and l.time = s.time\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs with [[label_name]] labels from all SIGs",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "with series as (\n  select distinct l.time as time,\n    r.sig_mentions_labels_name_with_all as metric_name,\n    r.sig_mentions_labels_value_with_all as metric_value\n  from\n    sprs_labels_by_sig l,\n    tsig_mentions_labels_with_all r\n  where\n    $__timeFilter(l.time)\n    and r.sig_mentions_labels_name_with_all != 'All'\n)\nselect\n  s.time as time,\n  s.metric_name as metric,\n  coalesce(l.value, 0) as value\nfrom\n  series s\nleft join\n  sprs_labels_by_sig l\non\n  l.series = 'prsiglbl' || s.metric_value || '[[label]]'                     \n  and l.time = s.time\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs from [[sig_name]] (having at least one of specified labels)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /^[[repogroups]]: / FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "with series as (\n  select distinct l.time as time,\n    lt.pr_labels_tags_name as metric_name,\n    lt.pr_labels_tags_value as metric_value\n  from\n    sprs_labels_by_sig l,\n    tpr_labels_tags lt\n  where\n    $__timeFilter(l.time)\n    and lt.pr_labels_tags_name != 'All labels combined'\n)\nselect\n  s.time as time,\n  s.metric_name as metric,\n  coalesce(l.value, 0) as value\nfrom\n  series s\nleft join\n  sprs_labels_by_sig l\non\n  l.series = 'prsiglbl[[sig]]' || s.metric_value           \n  and l.time = s.time\norder by\n  time"
    }
   ]
  },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 }, "content": "${docs:raw}" }
 ]
}