{
 "title": "PRs labels repository groups",
 "tags": [
  "dashboard",
  "kubernetes",
  "PRs",
  "repogroups"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "select all_combined_repo_group_name from tall_combined_repo_groups order by 1"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   {
    "name": "label_name",
    "label": "Label",
    "query": "select pr_labels_tags_name from tpr_labels_tags order by 1"
   },
   {
    "name": "repogroup",
    "query": "select all_combined_repo_group_value from tall_combined_repo_groups where all_combined_repo_group_name = '[[repogroup_name]]'"
   },
   {
    "name": "label",
    "query": "select pr_labels_tags_value from tpr_labels_tags where pr_labels_tags_name = '[[label_name]]'"
   }
  ]
 },
 "panels": [
  {
   "title": "PRs from [[repogroup_name]] repo group with [[label_name]]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select /^[[repogroups]]: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value\nfrom\n  sprs_labels\nwhere\n  $__timeFilter(time)\n  and series = 'prlbl[[repogroup]][[label]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs from [[repogroup_name]] repo group with [[label_name]]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select /^[[repogroups]]: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value\nfrom\n  sprs_labels\nwhere\n  $__timeFilter(time)\n  and series = 'prlbl[[repogroup]][[label]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs from [[repogroup_name]] repo group with [[label_name]]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /^[[repogroups]]: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"[[repogroup_name]]: [[label_name]]\"\nfrom\n  sprs_labels\nwhere\n  $__timeFilter(time)\n  and series = 'prlbl[[repogroup]][[label]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs with [[label_name]] labels from all repos",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "with series as (\n  select distinct l.time as time,\n    r.all_combined_repo_group_name as metric_name,\n    r.all_combined_repo_group_value as metric_value\n  from\n    sprs_labels l,\n    tall_combined_repo_groups r\n  where\n    $__timeFilter(l.time)\n    and r.all_combined_repo_group_name != 'All repos combined'\n)\nselect\n  s.time as time,\n  s.metric_name as metric,\n  coalesce(l.value, 0) as value\nfrom\n  series s\nleft join\n  sprs_labels l\non\n  l.series = 'prlbl' || s.metric_value || '[[label]]'                     \n  and l.time = s.time\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs from [[repogroup_name]] repo group (having at least one of specified labels)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /^[[repogroups]]: / FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "with series as (\n  select distinct l.time as time,\n    lt.pr_labels_tags_name as metric_name,\n    lt.pr_labels_tags_value as metric_value\n  from\n    sprs_labels l,\n    tpr_labels_tags lt\n  where\n    $__timeFilter(l.time)\n    and lt.pr_labels_tags_name != 'All labels combined'\n)\nselect\n  s.time as time,\n  s.metric_name as metric,\n  coalesce(l.value, 0) as value\nfrom\n  series s\nleft join\n  sprs_labels l\non\n  l.series = 'prlbl[[repogroup]]' || s.metric_value           \n  and l.time = s.time\norder by\n  time"
    }
   ]
  },
  {
   "title": "Percent PRs with [[label_name]] labels from all repos",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "with series as (\n  select distinct l.time as time,\n    r.all_combined_repo_group_name as metric_name,\n    r.all_combined_repo_group_value as metric_value\n  from\n    sprs_labels l,\n    tall_combined_repo_groups r\n  where\n    $__timeFilter(l.time)\n    and r.all_combined_repo_group_name != 'All repos combined'\n)\nselect\n  s.time as time,\n  s.metric_name as metric,\n  coalesce(l.value, 0) as value\nfrom\n  series s\nleft join\n  sprs_labels l\non\n  l.series = 'prlbl' || s.metric_value || '[[label]]'                     \n  and l.time = s.time\norder by\n  time"
    }
   ]
  },
  {
   "title": "Percent PRs from [[repogroup_name]] repo group (having at least one of specified labels)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /^[[repogroups]]: / FROM \"prs_labelled_d\" WHERE $timeFilter",
     "rawSql": "with series as (\n  select distinct l.time as time,\n    lt.pr_labels_tags_name as metric_name,\n    lt.pr_labels_tags_value as metric_value\n  from\n    sprs_labels l,\n    tpr_labels_tags lt\n  where\n    $__timeFilter(l.time)\n    and lt.pr_labels_tags_name != 'All labels combined'\n)\nselect\n  s.time as time,\n  s.metric_name as metric,\n  coalesce(l.value, 0) as value\nfrom\n  series s\nleft join\n  sprs_labels l\non\n  l.series = 'prlbl[[repogroup]]' || s.metric_value           \n  and l.time = s.time\norder by\n  time"
    }
   ]
  }
 ]
}