{
 "title": "PRs labels by repository groups",
 "tags": [
  "dashboard",
  "kubernetes",
  "PRs"
 ],
 "time": { "from": "now-30M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repogroups",
    "label": "Repository group",
    "query": "SHOW TAG VALUES WITH KEY = all_combined_repo_group_name"
   },
   {
    "name": "full_name",
    "query": "SHOW TAG VALUES WITH KEY = full_name"
   },
   {
    "name": "labels",
    "label": "Label",
    "query": "All labels combined,needs-rebase,needs-ok-to-test,do-not-merge,cla: no,release-note-label-needed"
   }
  ]
 },
 "panels": [
  {
   "title": "PRs from [[repogroups]] repo group with [[labels]]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select /^[[repogroups]]: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PRs from [[repogroups]] repo group with [[labels]]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select /^[[repogroups]]: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PRs from [[repogroups]] repo group with [[labels]]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /^[[repogroups]]: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PRs with [[labels]] labels from all repos",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PRs from [[repogroups]] repo group (having at least one of specified labels)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /^[[repogroups]]: / FROM \"prs_labelled_d\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Percent PRs from [[repogroups]] repo group with [[labels]]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /^[[repogroups]]: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Percent PRs with [[labels]] labels from all repos",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /: [[labels]]$/ FROM \"prs_labelled_d\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Percent PRs from [[repogroups]] repo group (having at least one of specified labels)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "PRs" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "prs_kubernetes_kubernetes_d",
     "query": "select /^[[repogroups]]: / FROM \"prs_labelled_d\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}