{
 "title": "SIG mentions using labels",
 "tags": [
  "dashboard",
  "kubernetes",
  "SIGs"
 ],
 "time": { "from": "now-10M", "to": "now" },
 "templating": {
  "list": [
   { "name": "period", "label": "Period", "query": "d,w,m,q,y" },
   {
    "name": "sig_name",
    "label": "SIG",
    "query": "select sig_mentions_labels_name from tsig_mentions_labels order by 1"
   },
   {
    "name": "kinds",
    "label": "Category",
    "query": "select '\"' || sig_mentions_labels_kind_name || '\"' from tsig_mentions_labels_kinds order by 1"
   },
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   {
    "name": "docs",
    "query": "select value_s from gha_vars where name = 'sig_mentions_labels_docs_html'"
   },
   {
    "name": "sig",
    "query": "select sig_mentions_labels_value from tsig_mentions_labels where sig_mentions_labels_name = '[[sig_name]]'"
   }
  ]
 },
 "panels": [
  {
   "title": "SIG [[sig_name]] categories ([[period]])",
   "type": "graph",
   "description": "Shows how many issues for SIG [[sig]] are labeled with given SIG category/kind.",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Issues count" }
   ],
   "targets": [
    {
     "measurement": "sig_federation_d",
     "query": "SELECT /^[[sig]]-[[kinds]]$/ FROM \"sig_mentions_labels_sig_kind_[[period]]\" WHERE $timeFilter",
     "rawSql": "with series as (\n  select distinct lsk.time,\n    lk.sig_mentions_labels_kind_name as metric_name,\n    lk.sig_mentions_labels_kind_value as metric_value\n  from\n    ssigm_lsk lsk,\n    tsig_mentions_labels_kinds lk\n  join (\n    select trim(both '\"' from unnest(string_to_array('${kinds:csv}', ','))) as kind\n  ) kinds\n  on\n    kinds.kind = lk.sig_mentions_labels_kind_name\n  where\n    $__timeFilter(lsk.time)\n    and lsk.period = '[[period]]'\n)\nselect\n  s.time as time,\n  '[[sig]]-' || s.metric_name as metric,\n  coalesce(lsk.value, 0) as value\nfrom\n  series s\nleft join\n  ssigm_lsk lsk\non\n  lsk.series = 'sigm_lsk[[sig]]' || s.metric_value\n  and lsk.time = s.time\n  and lsk.period = '[[period]]'\norder by\n  s.time"
    }
   ]
  },
  {
   "title": "All SIGs categories ([[period]])",
   "type": "graph",
   "description": "Shows how many issues are labeled with given SIG category/kind.",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Issues count" }
   ],
   "targets": [
    {
     "measurement": "sig_federation_d",
     "query": "SELECT /^[[kinds]]$/ FROM \"sig_mentions_labels_kind_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  ${kinds:csv}\nfrom\n  ssigm_lk\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "SIG mentions (all categories, [[period]])",
   "type": "graph",
   "description": "Shows how many issues are labeled with given SIG.",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Issues count" }
   ],
   "targets": [
    {
     "measurement": "sig_federation_d",
     "query": "SELECT * FROM \"sig_mentions_labels_sig_[[period]]\" WHERE $timeFilter",
     "rawSql": "with series as (\n  select distinct ls.time,\n    l.sig_mentions_labels_name as metric_name,\n    l.sig_mentions_labels_name as metric_value\n  from\n    ssigm_ls ls,\n    tsig_mentions_labels l\n  where\n    $__timeFilter(ls.time)\n    and ls.period = '[[period]]'\n)\nselect\n  s.time as time,\n  s.metric_name as metric,\n  coalesce(ls.value, 0) as value\nfrom\n  series s\nleft join\n  ssigm_ls ls\non\n  ls.series = 'sigm_ls' || s.metric_value\n  and ls.time = s.time\n  and ls.period = '[[period]]'\norder by\n  s.time"
    }
   ]
  },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "h": 13, "w": 24, "x": 0, "y": 57 }, "content": "[[docs]]" }
 ]
}