apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "devstats-${TIMESTAMP}"
spec:
  schedule: "${CRON}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - devstats
            env:
            - name: ONLY
              value: "${ONLY}"
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: pg-db
                  key: PG_HOST.secret
            - name: GHA2DB_USE_ES
              value: "1"
            - name: GHA2DB_GITHUB_OAUTH
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: GHA2DB_GITHUB_OAUTH.secret
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: pg-db
                  key: PG_PORT.secret
            - name: GHA2DB_USE_ES_RAW
              value: "1"
            - name: GHA2DB_ES_URL
              valueFrom:
                secretKeyRef:
                  name: es-db
                  key: GHA2DB_ES_URL.secret
            - name: GHA2DB_PROPAGATE_ONLY_VAR
              value: "1"
            - name: GHA2DB_PROJECTS_YAML
              value: k8s/projects.yaml
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-db
                  key: PG_DB.secret
            image: lukaszgryglicki/devstats-minimal
            imagePullPolicy: Always
            name: "devstats-${TIMESTAMP}"
          restartPolicy: Never
