kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devstats-git
  labels:
    name: devstats
  annotations:
    volume.beta.kubernetes.io/storage-class: efs
spec:
  storageClassName: efs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
