{
 "title": "Summary Dashboard",
 "tags": [
  "dashboard",
  "falco"
 ],
 "time": { "from": "now-6M", "to": "now-1w" },
 "templating": {
  "list": [
   {
    "name": "full_name",
    "query": "select value_s from gha_vars where name = 'full_name'"
   },
   { "name": "period", "label": "Period", "query": "d,w,m,q,y" },
   {
    "name": "repo_name",
    "label": "Repository",
    "query": "select top_repo_names_name from ttop_repo_names order by 1"
   },
   {
    "name": "repo",
    "query": "select top_repo_names_value from ttop_repo_names where top_repo_names_name = '[[repo_name]]'"
   },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "select all_repo_group_name from tall_repo_groups order by 1"
   },
   {
    "name": "repogroup",
    "query": "select all_repo_group_value from tall_repo_groups where all_repo_group_name = '[[repogroup_name]]'"
   },
   {
    "name": "repogroups",
    "label": "Repository groups",
    "query": "select '\"' || repo_group_name || '\"' from trepo_groups order by 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Community stats (Repository: [[repo_name]], [[period]])",
   "type": "graph",
   "description": "Community stats (Repository: [[repo_name]], [[period]])",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Stargazers" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "query": "SELECT \"value\" FROM \"autogen\".\"contrib_[[repogroup]]_watchers_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Stargazers\"\nfrom\n  swatchers\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'watch[[repo]]watch'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"autogen\".\"contrib_[[repogroup]]_forks_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Forks\"\nfrom\n  swatchers\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'watch[[repo]]forks'\norder by\n  time",
     "measurement": "reviewers_d"
    },
    {
     "rawSql": "select\n  time,\n  value as \"Open issues and PRs\"\nfrom\n  swatchers\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'watch[[repo]]opiss'\norder by\n  time",
     "query": "SELECT \"value\" FROM \"autogen\".\"contrib_[[repogroup]]_open_issues_[[period]]\" WHERE $timeFilter",
     "measurement": "reviewers_d"
    }
   ]
  },
  {
   "title": "Contributing companies and developers (Repository group: [[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Contributing companies and developers (Repository group: [[repogroup_name]], [[period]])",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Companies" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"autogen\".\"num_stats_[[repogroup]]_companies_[[period]]\" WHERE $timeFilter",
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"Number of contributing companies\"\nfrom\n  snum_stats\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'nstats[[repogroup]]comps'\norder by\n  time",
     "alias": "Number of contributing companies"
    },
    {
     "query": "SELECT \"value\" FROM \"autogen\".\"num_stats_[[repogroup]]_developers_[[period]]\" WHERE $timeFilter",
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"Number of contributing developers\"\nfrom\n  snum_stats\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'nstats[[repogroup]]devs'\norder by\n  time",
     "alias": "Number of contributing developers"
    }
   ]
  },
  {
   "title": "PRs merged per repository groups ([[repogroups]], [[period]])",
   "type": "graph",
   "description": "Number of PRs merged in given repository group",
   "gridPos": { "x": 0, "y": 14, "h": 9, "w": 24 },
   "yaxes": [
    { "format": "short", "label": "Pull requests merged" }
   ],
   "targets": [
    {
     "measurement": "notused",
     "query": "SELECT /^[[repogroups]]$/ FROM \"group_prs_merged_[[period]]\" WHERE $timeFilter",
     "alias": "$col",
     "rawSql": "select\n  time,\n  ${repogroups:csv}\nfrom\n  sgrp_pr_merg\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "PRs merged in all [[full_name]] repositories ([[period]])",
   "type": "graph",
   "description": "PRs merged in all [[full_name]] repositories",
   "gridPos": { "y": 23, "h": 12, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "PRs merged" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"all_prs_merged_[[period]]\" WHERE $timeFilter",
     "alias": "PRs merged",
     "measurement": "all_prs_merged_h",
     "rawSql": "select\n  time,\n  \"value\" as \"All PRs merged\"\nfrom\n  sall_prs_merged\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Issues Repository group: [[repogroup_name]] ([[period]])",
   "type": "graph",
   "description": "Show Issues opened/closed for given repository group",
   "gridPos": { "x": 12, "y": 23, "h": 12, "w": 12 },
   "yaxes": [
    { "format": "short", "label": "Issues" }
   ],
   "targets": [
    {
     "measurement": "sig_federation_d",
     "rawSql": "select\n  time,\n  \"[[repogroup]]\" as \"Issues opened\"\nfrom\n  siopened\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\norder by\n  time",
     "query": "SELECT /^[[repogroup]]$/ FROM \"issues_opened_[[period]]\" WHERE $timeFilter"
    },
    {
     "rawSql": "select\n  time,\n  \"[[repogroup]]\" as \"Issues closed\"\nfrom\n  siclosed\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\norder by\n  time",
     "measurement": "sig_federation_d",
     "query": "SELECT /^[[repogroup]]$/ FROM \"issues_closed_[[period]]\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Time before any comments or activities from someone other than the author (Repository group: [[repogroup_name]], [[period]])",
   "type": "graph",
   "description": "Time before any comments or activities from someone other than the author",
   "gridPos": { "x": 0, "y": 35, "h": 12, "w": 12 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"85th percentile time\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]]p85'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]]med'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"15th percentile time\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]]p15'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Time to first non-author activity (Repository group: [[repogroup_name]], [[period]])",
   "type": "table",
   "description": "Time to first non-author activity",
   "gridPos": { "y": 35, "h": 12, "w": 12, "x": 12 },
   "targets": [
    {
     "rawSql": "select\n  time as \"Time\",\n  descr as \"15th percentile\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]]p15'\norder by\n  time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_percentile_15_[[period]]\" WHERE $timeFilter"
    },
    {
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_median_[[period]]\" WHERE $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select\n  time as \"Time\",\n  descr as \"Median\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]]med'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time as \"Time\",\n  descr as \"85th percentile\"\nfrom\n  sfirst_non_author\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'non_auth[[repogroup]]p85'\norder by\n  time",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"non_author_[[repogroup]]_percentile_85_[[period]]\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Current median time to close for issues created last [[period]] for repository group [[repogroup_name]]",
   "type": "singlestat",
   "description": "Current median closing time for recent issues.",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "SELECT \"descr\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  descr\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]allm'\norder by\n  time desc\nlimit 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ]
    }
   ]
  },
  {
   "title": "Number of closed issues opened last [[period]] for repository group [[repogroup_name]]",
   "type": "singlestat",
   "description": "Number of closed issues opened recently.",
   "gridPos": { "x": 12, "y": 47, "h": 2, "w": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time, value\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]alln'\norder by\n  time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Number/Median time to close of Issues in [[repogroup_name]] repository group ([[period]])",
   "type": "graph",
   "description": "Median time to close and number of issues created in [[repogroup]] repository group.",
   "gridPos": { "x": 0, "y": 49, "h": 11, "w": 12 },
   "yaxes": [
    { "format": "h", "label": "Median issue close time" }
   ],
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"Average number of issues opened\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]alln'\norder by\n  time"
    },
    {
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
     "measurement": "reviewers_d",
     "rawSql": "select\n  time,\n  value as \"Median time to close issue\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]allm'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Number/Median time to close of Issues in [[repogroup_name]] repository group ([[period]])",
   "type": "table",
   "description": "Median time to close and the number​ of issues created in [[repogroup]] repository group.",
   "gridPos": { "x": 12, "y": 49, "h": 11, "w": 12 },
   "targets": [
    {
     "query": "SELECT \"descr\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "type": "fill", "params": [ "null" ] }
     ],
     "rawSql": "select\n  time as \"Time\",\n  descr as \"Median time to close issue\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]allm'\norder by\n  time"
    },
    {
     "rawSql": "select\n  time as \"Time\",\n  value as \"Average number of issues opened\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]]alln'\norder by\n  time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter"
    }
   ]
  }
 ]
}