#!/bin/bash
PG_DB=gha PG_HOST=localhost IDB_DB=gha IDB_HOST=localhost GHA2DB_LOCAL=1 GHA2DB_PROJECTS_YAML=./kubernetes.yaml GHA2DB_GITHUB_OAUTH="-" GHA2DB_GHAPISKIP=1 GHA2DB_AECLEANSKIP=1 GHA2DB_GETREPOSSKIP=1 ./devstats
