{{- $skipProvisions := .Values.skipProvisions -}}
{{ if not $skipProvisions }}
{{- $root := . -}}
{{- range $index, $_ := .Values.projects -}}
{{- if and (or (eq ($index|int) ($root.Values.indexProvisionsFrom|int)) (gt ($index|int) ($root.Values.indexProvisionsFrom|int))) (lt ($index|int) ($root.Values.indexProvisionsTo|int)) -}}
---
apiVersion: v1
kind: Pod
metadata:
  name: '{{ $root.Values.provisionPodName }}-{{ .proj }}'
  labels:
    type: 'provision'
    proj: {{ .proj }}
{{- with $root.Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ $root.Chart.Name }}
    helm.sh/chart: {{ printf "%s-%s" $root.Chart.Name $root.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
spec:
  containers:
  - command:
    - {{ $root.Values.provisionCommand }}
{{ if $root.Values.provisionCommandArgs }}
    args:
{{- with $root.Values.provisionCommandArgs -}}
{{ toYaml . | nindent 6 }}
{{ end }}
{{ end }}
{{ if $root.Values.useProvisionsResourcesLimits }}
    resources:
      requests:
        memory: '{{ $root.Values.requestsProvisionsMemory }}'
        cpu: '{{ $root.Values.requestsProvisionsCPU }}'
      limits:
        memory: '{{ $root.Values.limitsProvisionsMemory }}'
        cpu: '{{ $root.Values.limitsProvisionsCPU }}'
{{ end }}
    env:
    - name: PROJ
      value: {{ .proj }}
    - name: PROJDB
      value: {{ .db }}
    - name: PROJREPO
      value: '{{ .repo }}'
    - name: SKIPTEMP
      value: "1"
    - name: NOLOCK
      value: "1"
    - name: NOBACKUP
      value: "1"
    - name: SKIPADDALL
      value: "1"
    - name: TEST_SERVER
      value: "1"
    - name: ONLY
      value: {{ .proj }}
    - name: WAITBOOT
      value: '{{ $root.Values.waitForBootstrap }}'
    - name: GHA2DB_NCPUS
      value: '{{ $root.Values.nCPUs }}'
    - name: GHA2DB_USE_ES
      value: '{{ $root.Values.useES }}'
    - name: GHA2DB_USE_ES_RAW
      value: '{{ $root.Values.useESRaw }}'
    - name: GHA2DB_ES_BULK_SIZE
      value: '{{ $root.Values.esBulkSize }}'
    - name: GHA2DB_DEBUG
      value: '{{ $root.Values.debug }}'
    - name: GHA2DB_CMDDEBUG
      value: '{{ $root.Values.cmdDebug }}'
    - name: GHA2DB_GITHUB_DEBUG
      value: '{{ $root.Values.githubDebug }}'
    - name: GHA2DB_QOUT
      value: '{{ $root.Values.queryOut }}'
    - name: GHA2DB_REPOS_DIR
      value: '{{ $root.Values.reposDir }}'
    - name: GHA2DB_COMPANY_ACQ_YAML
      value: '{{ $root.Values.companyAcq }}'
    - name: GHA2DB_PROJECTS_YAML
      value: {{ $root.Values.projectsFile }}
    - name: GHA2DB_AFFILIATIONS_JSON
      value: '{{ $root.Values.affiliations }}'
    - name: GHA2DB_COMPUTE_ALL
      value: '{{ $root.Values.forceComputeAll }}'
    - name: GHA2DB_SKIP_METRICS
      value: '{{ $root.Values.skipMetrics }}'
    - name: GHA2DB_ONLY_METRICS
      value: '{{ $root.Values.onlyMetrics }}'
    - name: GHA2DB_FORCE_PERIODS
      value: '{{ $root.Values.periods }}'
    - name: GHA2DB_GITHUB_OAUTH
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.oauthSecret }}
          key: GHA2DB_GITHUB_OAUTH.secret
    - name: ES_PORT
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.esSecret }}
          key: ES_PORT.secret
    - name: ES_HOST
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.esSecret }}
          key: ES_HOST.secret
    - name: ES_PROTO
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.esSecret }}
          key: ES_PROTO.secret
    - name: PG_HOST
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_HOST.secret
    - name: PG_PORT
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_PORT.secret
    - name: PG_PASS
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_PASS.secret
    - name: PG_PASS_RO
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_PASS_RO.secret
    - name: PG_PASS_TEAM
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_PASS_TEAM.secret
    - name: PG_ADMIN_USER
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_ADMIN_USER.secret
    image: {{ $root.Values.proivisionImage }}
    imagePullPolicy: {{ $root.Values.imagePullPolicy }}
    name: '{{ $root.Values.provisionPodName }}-{{ .proj }}'
    volumeMounts:
    - name: {{ $root.Values.volumeMountName }}
      mountPath: '{{ $root.Values.volumeMountPath }}'
  volumes:
  - name: {{ $root.Values.volumeName }}
    persistentVolumeClaim:
      claimName: {{ $root.Values.pvName }}
  restartPolicy: {{ $root.Values.provisionRestartPolicy }}
  nodeSelector:
{{- with $root.Values.nodeSelector -}}
{{ toYaml . | nindent 4 }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
