{{- $skipProvisions := .Values.skipProvisions -}}
{{ if not $skipProvisions }}
{{- $root := . -}}
{{- range $index, $_ := .Values.projects -}}
---
apiVersion: v1
kind: Pod
metadata:
  name: '{{ $root.Values.provisionPodName }}-{{ .proj }}'
  labels:
    proj: {{ .proj }}
{{- with $root.Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ $root.Chart.Name }}
    helm.sh/chart: {{ printf "%s-%s" $root.Chart.Name $root.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
spec:
  containers:
  - command:
    - {{ $root.Values.provisionCommand }}
    env:
    - name: PROJ
      value: {{ .proj }}
    - name: PROJDB
      value: {{ .db }}
    - name: PROJREPO
      value: '{{ .repo }}'
    - name: SKIPTEMP
      value: "1"
    - name: NOLOCK
      value: "1"
    - name: NOBACKUP
      value: "1"
    - name: SKIPADDALL
      value: "1"
    - name: TEST_SERVER
      value: "1"
    - name: ONLY
      value: {{ .proj }}
    - name: WAITBOOT
      value: '{{ $root.Values.waitForBootstrap }}'
    - name: GHA2DB_GITHUB_OAUTH
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.oauthSecret }}
          key: GHA2DB_GITHUB_OAUTH.secret
    - name: ES_PORT
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.esSecret }}
          key: ES_PORT.secret
    - name: ES_HOST
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.esSecret }}
          key: ES_HOST.secret
    - name: ES_PROTO
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.esSecret }}
          key: ES_PROTO.secret
    - name: PG_HOST
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_HOST.secret
    - name: PG_PORT
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_PORT.secret
    - name: PG_PASS
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_PASS.secret
    - name: PG_PASS_RO
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_PASS_RO.secret
    - name: PG_PASS_TEAM
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_PASS_TEAM.secret
    - name: PG_ADMIN_USER
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.pgSecret }}
          key: PG_ADMIN_USER.secret
    image: {{ $root.Values.proivisionImage }}
    imagePullPolicy: {{ $root.Values.imagePullPolicy }}
    name: '{{ $root.Values.provisionPodName }}-{{ .proj }}'
    volumeMounts:
    - name: {{ $root.Values.volumeMountName }}
      mountPath: '{{ $root.Values.volumeMountPath }}'
  volumes:
  - name: {{ $root.Values.volumeName }}
    persistentVolumeClaim:
      claimName: {{ $root.Values.pvName }}
  restartPolicy: {{ $root.Values.bootstrapRestartPolicy }}
{{ end }}
{{ end }}
