{{- $skipCrons := .Values.skipCrons -}}
{{ if not $skipCrons }}
{{- $root := . -}}
{{- range $index, $_ := .Values.projects -}}
{{- if and (or (eq ($index|int) ($root.Values.indexCronsFrom|int)) (gt ($index|int) ($root.Values.indexCronsFrom|int))) (lt ($index|int) ($root.Values.indexCronsTo|int)) -}}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: '{{ $root.Values.syncPodName }}-{{ .proj }}'
  labels:
    type: 'cron'
    proj: {{ .proj }}
{{- with $root.Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ $root.Chart.Name }}
    helm.sh/chart: {{ printf "%s-%s" $root.Chart.Name $root.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
spec:
  schedule: '{{ .cron }}'
  concurrencyPolicy: {{ $root.Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: '{{ $root.Values.syncPodName }}-{{ .proj }}'
          labels:
            type: 'sync'
            proj: {{ .proj }}
{{- with $root.Values.labels -}}
{{ toYaml . | nindent 12 }}
{{ end }}
            app.kubernetes.io/name: {{ $root.Chart.Name }}
            helm.sh/chart: {{ printf "%s-%s" $root.Chart.Name $root.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
            app.kubernetes.io/instance: {{ $root.Release.Name }}
            app.kubernetes.io/managed-by: {{ $root.Release.Service }}
        spec:
          containers:
          - command:
            - {{ $root.Values.syncCommand }}
{{ if $root.Values.syncCommandArgs }}
            args:
{{- with $root.Values.syncCommandArgs -}}
{{ toYaml . | nindent 14 }}
{{ end }}
{{ end }}
{{ if $root.Values.useResourcesLimits }}
            resources:
              requests:
                memory: '{{ $root.Values.requestsMemory }}'
                cpu: '{{ $root.Values.requestsCPU }}'
              limits:
                memory: '{{ $root.Values.limitsMemory }}'
                cpu: '{{ $root.Values.limitsCPU }}'
{{ end }}
            env:
            - name: ONLY
              value: {{ .proj }}
            - name: GHA2DB_USE_ES
              value: '{{ $root.Values.useES }}'
            - name: GHA2DB_USE_ES_RAW
              value: '{{ $root.Values.useESRaw }}'
            - name: GHA2DB_PROPAGATE_ONLY_VAR
              value: "1"
            - name: GHA2DB_CHECK_PROVISION_FLAG
              value: "1"
            - name: GHA2DB_NCPUS
              value: '{{ $root.Values.nCPUs }}'
            - name: GHA2DB_ES_BULK_SIZE
              value: '{{ $root.Values.esBulkSize }}'
            - name: GHA2DB_DEBUG
              value: '{{ $root.Values.debug }}'
            - name: GHA2DB_CMDDEBUG
              value: '{{ $root.Values.cmdDebug }}'
            - name: GHA2DB_GITHUB_DEBUG
              value: '{{ $root.Values.githubDebug }}'
            - name: GHA2DB_QOUT
              value: '{{ $root.Values.queryOut }}'
            - name: GHA2DB_REPOS_DIR
              value: '{{ $root.Values.reposDir }}'
            - name: GHA2DB_COMPANY_ACQ_YAML
              value: '{{ $root.Values.companyAcq }}'
            - name: GHA2DB_AFFILIATIONS_JSON
              value: '{{ $root.Values.affiliations }}'
            - name: GHA2DB_COMPUTE_ALL
              value: '{{ $root.Values.forceComputeAll }}'
            - name: GHA2DB_SKIP_METRICS
              value: '{{ $root.Values.skipMetrics }}'
            - name: GHA2DB_ONLY_METRICS
              value: '{{ $root.Values.onlyMetrics }}'
            - name: GHA2DB_FORCE_PERIODS
              value: '{{ $root.Values.periods }}'
            - name: GHA2DB_PROJECTS_YAML
              value: {{ $root.Values.projectsFile }}
            - name: GHA2DB_GITHUB_OAUTH
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.oauthSecret }}
                  key: GHA2DB_GITHUB_OAUTH.secret
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.pgSecret }}
                  key: PG_HOST.secret
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.pgSecret }}
                  key: PG_PORT.secret
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.pgSecret }}
                  key: PG_PASS.secret
            - name: GHA2DB_ES_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.esSecret }}
                  key: GHA2DB_ES_URL.secret
            image: {{ $root.Values.syncImage }}
            imagePullPolicy: {{ $root.Values.imagePullPolicy }}
            name: '{{ $root.Values.syncPodName }}-{{ .proj }}'
            volumeMounts:
            - name: {{ $root.Values.volumeMountName }}
              mountPath: '{{ $root.Values.volumeMountPath }}'
          volumes:
          - name: {{ $root.Values.volumeName }}
            persistentVolumeClaim:
              claimName: {{ $root.Values.pvName }}
          restartPolicy: {{ $root.Values.syncRestartPolicy }}
          nodeSelector:
{{- with $root.Values.nodeSelector -}}
{{ toYaml . | nindent 12 }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
