---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvName }}
  labels:
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "devstats-helm.name" . }}
    helm.sh/chart: {{ include "devstats-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.storageClass }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - {{ .Values.storageAccessModes }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
