{{ $pgAdminUser := .Files.Get "secrets/PG_ADMIN_USER.secret" }}
{{ $pgHost := .Files.Get "secrets/PG_HOST.secret" }}
{{ $pgPass := .Files.Get "secrets/PG_PASS.secret" }}
{{ $pgPassRO := .Files.Get "secrets/PG_PASS_RO.secret" }}
{{ $pgPassTeam := .Files.Get "secrets/PG_PASS_TEAM.secret" }}
{{ $pgPort := .Files.Get "secrets/PG_PORT.secret" }}
{{ if and $pgAdminUser $pgHost $pgPass $pgPassRO $pgPassTeam $pgPort }}
---
apiVersion: v1
data:
  PG_ADMIN_USER.secret: {{ $pgAdminUser  | b64enc}}
  PG_HOST.secret: {{ $pgHost | b64enc }}
  PG_PASS.secret: {{ $pgPass | b64enc }}
  PG_PASS_RO.secret: {{ $pgPassRO | b64enc }}
  PG_PASS_TEAM.secret: {{ $pgPassTeam | b64enc }}
  PG_PORT.secret: {{ $pgPort | b64enc }}
kind: Secret
metadata:
  name: pg-db
  labels:
    app.kubernetes.io/name: {{ include "devstats-helm.name" . }}
    helm.sh/chart: {{ include "devstats-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
{{ else }}
missing_one_or_more_pg_secrets: "Please take a look at the NOTES.txt file"
{{ end }}
