apiVersion: v1
data:
  PG_ADMIN_USER.secret: {{ .Files.Get "secrets/PG_ADMIN_USER.secret" | b64enc }}
  PG_HOST.secret: {{ .Files.Get "secrets/PG_HOST.secret" | b64enc }}
  PG_PASS.secret: {{ .Files.Get "secrets/PG_PASS.secret" | b64enc }}
  PG_PASS_RO.secret: {{ .Files.Get "secrets/PG_PASS_RO.secret" | b64enc }}
  PG_PASS_TEAM.secret: {{ .Files.Get "secrets/PG_PASS_TEAM.secret" | b64enc }}
  PG_PORT.secret: {{ .Files.Get "secrets/PG_PORT.secret" | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: pg-db
  selfLink: /api/v1/namespaces/default/secrets/pg-db
type: Opaque
