{{- $pgAdminUser := .Files.Get "secrets/PG_ADMIN_USER.secret" -}}
{{- $pgHost := .Files.Get "secrets/PG_HOST.secret" -}}
{{- $pgPass := .Files.Get "secrets/PG_PASS.secret" -}}
{{- $pgPassRO := .Files.Get "secrets/PG_PASS_RO.secret" -}}
{{- $pgPassTeam := .Files.Get "secrets/PG_PASS_TEAM.secret" -}}
{{- $pgPort := .Files.Get "secrets/PG_PORT.secret" -}}
{{ if and $pgAdminUser $pgHost $pgPass $pgPassRO $pgPassTeam $pgPort }}
---
apiVersion: v1
data:
  PG_ADMIN_USER.secret: {{ $pgAdminUser | b64enc }}
  PG_HOST.secret: {{ $pgHost | b64enc }}
  PG_PASS.secret: {{ $pgPass | b64enc }}
  PG_PASS_RO.secret: {{ $pgPassRO | b64enc }}
  PG_PASS_TEAM.secret: {{ $pgPassTeam | b64enc }}
  PG_PORT.secret: {{ $pgPort | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.pgSecret }}
  labels:
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "devstats-helm.name" . }}
    helm.sh/chart: {{ include "devstats-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_one_or_more_pg_secrets: "Please take a look at the NOTES.txt file"
{{ end }}
{{- $esHost := .Files.Get "secrets/ES_HOST.secret" -}}
{{- $esPort := .Files.Get "secrets/ES_PORT.secret" -}}
{{- $esProto := .Files.Get "secrets/ES_PROTO.secret" -}}
{{- $esURL := .Files.Get "secrets/GHA2DB_ES_URL.secret" -}}
{{ if and $esHost $esPort $esProto $esURL }}
---
apiVersion: v1
data:
  ES_HOST.secret: {{ $esHost | b64enc }}
  ES_PORT.secret: {{ $esPort | b64enc }}
  ES_PROTO.secret: {{ $esProto | b64enc }}
  GHA2DB_ES_URL.secret: {{ $esURL | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.esSecret }}
  labels:
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "devstats-helm.name" . }}
    helm.sh/chart: {{ include "devstats-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_one_or_more_es_secrets: "Please take a look at the NOTES.txt file"
{{ end }}
{{- $token := .Files.Get "secrets/GHA2DB_GITHUB_OAUTH.secret" -}}
{{ if $token }}
---
apiVersion: v1
data:
  GHA2DB_GITHUB_OAUTH.secret: {{ $token | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.oauthSecret }}
  labels:
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "devstats-helm.name" . }}
    helm.sh/chart: {{ include "devstats-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_github_oauth_secret: "Please take a look at the NOTES.txt file"
{{ end }}
