{
 "title": "Issues age ES",
 "tags": [
  "dashboard",
  "cncf"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "full_name",
    "query": "{ \"find\": \"terms\", \"field\": \"vvalue\", \"query\": \"type:tvars AND vname:full_name\" }"
   },
   { "name": "period", "label": "Period", "query": "d,d7,w,m,q,y" },
   {
    "name": "repogroup_name",
    "label": "Repository group",
    "query": "{\"find\": \"terms\", \"field\": \"all_repo_group_name\", \"query\": \"type: tall_repo_groups\"}"
   },
   {
    "name": "repogroup",
    "query": "{ \"find\": \"terms\", \"field\": \"all_repo_group_value\", \"query\": \"type: tall_repo_groups AND all_repo_group_name:[[repogroup_name]]\" } "
   },
   {
    "name": "prio_name",
    "label": "Priority",
    "query": "{\"find\": \"terms\", \"field\": \"priority_labels_name_with_all\", \"query\": \"type: tpriority_labels_with_all\"}"
   },
   {
    "name": "prio",
    "label": "Priority",
    "query": "{ \"find\": \"terms\", \"field\": \"priority_labels_value_with_all\", \"query\": \"type: tpriority_labels_with_all AND priority_labels_name_with_all:[[prio_name]]\" } "
   },
   {
    "name": "docs",
    "query": "{\"find\": \"terms\", \"field\": \"vvalue\", \"query\": \"type:tvars AND vname: issues_age_docs_html\"}"
   },
   {
    "name": "es_period",
    "query": "{ \"find\": \"terms\", \"field\": \"es_period\", \"query\": \"type: tes_periods AND devstats_period:[[period]]\" } "
   }
  ]
 },
 "panels": [
  {
   "title": "Current median time to close for issues created last [[period]] for repository group [[repogroup_name]], Priority: [[prio_name]]",
   "type": "singlestat",
   "description": "Current median closing time for recent issues.",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "ivalue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "type:isissues_age AND period:[[period]] AND series:iage[[repogroup]][[prio]]m AND name:merged",
     "rawSql": "select\n  descr\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]][[prio]]m'\norder by\n  time desc\nlimit 1",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Number of closed issues opened last [[period]] for repository group [[repogroup_name]], Priority: [[prio_name]]",
   "type": "singlestat",
   "description": "Number of closed issues opened recently",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "time",
       "id": "2",
       "settings": { "interval": "[[es_period]]", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "ivalue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "type:isissues_age AND period:[[period]] AND series:iage[[repogroup]][[prio]]n AND name:merged",
     "rawSql": "select\n  time, value\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]][[prio]]n'\norder by\n  time desc\nlimit 1",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Number/Median time to close of Issues in [[repogroup_name]] repository group ([[period]]), Priority: [[prio_name]]",
   "type": "graph",
   "description": "Median time to close and number of issues created in [[repogroup]] repository group.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "h", "label": "Median issue close time" }
   ],
   "targets": [
    {
     "measurement": "reviewers_d",
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Average number of issues opened\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]][[prio]]n'\norder by\n  time"
    },
    {
     "measurement": "reviewers_d",
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time,\n  value as \"Median time to close issue\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]][[prio]]m'\norder by\n  time"
    }
   ]
  },
  {
   "title": "Number/Median time to close of Issues in [[repogroup_name]] repository group ([[period]]), Priority: [[prio_name]]",
   "type": "table",
   "description": "Median time to close and the number​ of issues created in [[repogroup]] repository group.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"descr\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_median_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  descr as \"Median time to close issue\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]][[prio]]m'\norder by\n  time"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"autogen\".\"issues_age_[[repogroup]]_[[prio]]_number_[[period]]\" WHERE $timeFilter",
     "rawSql": "select\n  time as \"Time\",\n  value as \"Average number of issues opened\"\nfrom\n  sissues_age\nwhere\n  $__timeFilter(time)\n  and period = '[[period]]'\n  and series = 'iage[[repogroup]][[prio]]n'\norder by\n  time"
    }
   ]
  },
  { "title": "Dashboard documentation", "type": "text", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 }, "content": "${docs:raw}" }
 ]
}